### ISSUE TITLE
MIGR v12 sale_isolated_quotation feature, RFC about what are the most generic features

### ISSUE THREAD

**Issue by bealdav** [OCA/sale-workflow#1033]
Hi all,

I need to migrate sale_quotation_number but with a small change.
sale_quotation_number populate `origin` field with name of the quote.

Instead, I would like use a m2o for that like in sale_isolated_quotation
https://github.com/OCA/sale-workflow/blob/11.0/sale_isolated_quotation/models/sale.py#L16

If I do that, I suppose than sale_isolated_quotation migration could be easier and reduce the lines of code.

Please let me know what do you think about ?

cc  @kittiu 

EDIT : finally only concern sale_isolated_quotation

**Comment by kittiu** [comment]
@bealdav I have some question.
The sale_quotation_number is just to keep the old quote name on origin text field, right?
* How can it use m2o, I don't quite get...
* How will it affect sale_isolated_quotation, both are quite unrelated isn't it?

**Comment by bealdav** [comment]
Sorry you're right, I've not reading the code carefully

On my side I just need to keep_isolated_quotation, thanks for this module for sure. But I think some features could be separated to have less complexity: 

- no more `substate2` , this field isn't updated automatically according workflow (mail sent) AFAIK => easier UI
- no more `action_convert_to_order`(): all managed in `action_confirm`() => easier UI
- no more `is_order` field because it's the state that defined if it's an order or not, don't you think ? And I suppose when you reset your order to a quotation, the state of this field is not managed, isn't it ?

Do you think I should make a base module without these features or are you agree with me that 3 feature above are additional features not required in minimal scenario ?

If you're agree, I can split in 2 modules ?
Have you suggestion about modules names ?

**Comment by kittiu** [comment]
@bealdav I do agree with you if anything will make it less complicated. I also don't like the fact about is_order or state2.
But I still not clear what you plan to do. You mean,

1. Make a simpler module as sale_quotation_number
2. Then the sale_isolated_quotation on top of it?

Sorry for my not understanding but what will the final product looks like exactly?

**Comment by bealdav** [comment]
Ok then according to your answer, the easier seems to be to port sale_isolated_quotation but removing is_order and state2 fields. 
Do you want than I do it ?

Thanks

**Comment by kittiu** [comment]
Ok, so you think it can be removed without reducing the feature, right?
Please go ahead and I will help review it. :)
Thanks!

**Comment by bealdav** [comment]
Finally (after migration process) your module match more with my customer use cases than I thought.

More additions (than i had in my head) could break things. Thanks

Just minor things after migration process https://github.com/OCA/sale-workflow/pull/1034

**Comment by bealdav** [comment]
@kittiu finally I think it could be better to rename, `is_order` as `order_sequence` because it's the real sense of this.

When is_order is True, you are by default in quotation state and when you click on convert_to_order() you're also in quotation state. That's confusing with is_order=True semantic, doesn't it

Then `order_sequence` is a more explicit name. 

What do you think ?

**Comment by kittiu** [comment]
I am ok, it is one improvement. Imigration script is needed for this, may be?

**Comment by bealdav** [comment]
yes for migration script.
