### ISSUE TITLE
Q: Sales Exception usage?

### ISSUE THREAD

**Issue by dreispt** [OCA/sale-workflow#1061]
Hello, I'm curious about the sale_exception module.
From the current Readme, I can't find my way to walk through the module's features.

Would the people familiar with it be kind enough to share more details on how to use it?

Thank you.

**Comment by pedrobaeza** [comment]
- Define an exception rule with a condition based on a formula.
- If the sales order meets that condition, it can't be confirmed and gets the exception state.
