### ISSUE TITLE
[12.0] sale_triple_discount bad result

### ISSUE THREAD

**Issue by igallart** [OCA/sale-workflow#1075]
In a sale order, when there are two or more lines, if are created joins, the result is different.

Try:

Price unit -> 1,300
Same product

Line1
Discount 1 -> 10
Discount 2 -> 20
Discount 3 -> 30

Line2
Discount 1 -> 10
Discount 2 -> 20
Discount 3 -> 30

Save

Total1 -> 655.20
Total2 -> 1170.0

**Comment by igallart** [comment]
I close the problem because although there are cases that fail, I have not found the problem, sometimes it works and sometimes it does not.

**Comment by julianram** [comment]
> I close the problem because although there are cases that fail, I have not found the problem, sometimes it works and sometimes it does not.

Hi @igallart .

We have the same problem, something is wrong with the caches, did you find a solution?

**Comment by igallart** [comment]
@JulianaPoudou , if I remember correctly, what we did was use the module as it was before, without the latest refactorings.
