### ISSUE TITLE
[12.0] new module pricelist_by_category_qty

### ISSUE THREAD

**Issue by mayjo79** [OCA/sale-workflow#1078]
This module was originally developed in v7.0 by the company Julius : https://github.com/julius-network-solutions/julius-openobject-addons/tree/master/pricelist_by_category_qty
It has just been migrated to version 12 : https://github.com/mayjo79/odoo-addons/tree/12.0/pricelist_by_category_qty
I would like to deliver this module to OCA.
I had the agreement of Mathieu Vatel of the Julius company.
In addition, he confirms to me that Julius signed the CLA when OCA was created.

**Comment by bealdav** [comment]
cc @rousseldenis

**Comment by sbidoul** [comment]
@mayjo79 I confirm there is an Enterprise CLA for Julius Network Solutions.
So go ahead and open a PR. Just pay attention to preserve de commit history of the original module.
You can then ask @mathieuvatel to approve the PR.

**Comment by mayjo79** [comment]
Can you explain to me how to keep only the history of this original module when it is part with other modules of the repository: https://github.com/julius-network-solutions/julius-openobject-addons
Thanks

**Comment by sbidoul** [comment]
I think you can apply a variant of a [standard module migration procedure](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0) by pointing to the julius-network-solutions repo:

```git format-patch --keep-subject --stdout origin/12.0..julius-network-solutions/7.0 -- <module path> | git am -3 --keep```

**Comment by mayjo79** [comment]
Sorry but I'm not comfortable with git format-patch 
When I execute :

> git format-patch --keep-subject --stdout origin/12.0..julius-network-solutions/8.0  -- julius-openobject-addons/pricelist_by_category_qty | git am -3 --keep

I have the error :

> fatal: bad revision 'origin/12.0..julius-network-solutions/8.0'

Could you help me ?
Thanks

**Comment by bealdav** [comment]
If you want an easier procedure, you may copy/paste original julius code in sale-workflow fork and make `git commit -m "ADD this module" --author "Author <author@company.fr>` and apply your modification with meld and commit again with you as author.

**Comment by rousseldenis** [comment]
> I have the error :
> 
> > fatal: bad revision 'origin/12.0..julius-network-solutions/8.0'
> 
> Could you help me ?
> Thanks

You need to add the remotes and fetch them before launching git format-patch command.

https://help.github.com/en/github/using-git/adding-a-remote

**Comment by mayjo79** [comment]
@bealdav I hope I followed what you told me. Before creating the PR, can you tell me if it's good ?
https://github.com/mayjo79/sale-workflow

@rousseldenis Sorry, I saw your message too late.

**Comment by bealdav** [comment]
I think it's correct from my point of view, at least it's one of your first contribution then this simplify procedure could be sufficient. Thanks a lot. 

Please make a PR now, there are some typo to fix after the review

**Comment by mayjo79** [comment]
I just created the PR https://github.com/OCA/sale-workflow/pull/1083
