### ISSUE TITLE
[12.0] Sales Double Validation broken

### ISSUE THREAD

**Issue by w18g** [OCA/sale-workflow#1087]
Sales person can "confirm" order without approval process.

It is only set to approve if a quotation is saved but can skip if confirmed right away.

Also there is not a disapproval flow.

**Comment by pedrobaeza** [comment]
Odoo version?

**Comment by w18g** [comment]
Sorry odoo 12.0

**Comment by jcdrubay** [comment]
It does not support either this workflow:

 - Create the Quotation below the limit + Save
- Edit and change the total price above the limit

The user can then still confirm the order.

**Comment by jcdrubay** [comment]
The Duplicate is not supported either:

Create the order above the limit => user needs to get an approval
User duplicates the order => user does not need to get an approval for the duplicated order

**Comment by rousseldenis** [comment]
@pedrobaeza There is something weird for me in the create() method. I put a comment there https://github.com/OCA/sale-workflow/commit/0f96f1468ad793fb58de855bf9b8a44b7fa2ddb1#r43264003

**Comment by pedrobaeza** [comment]
OK, I was doing just the initial issue classification.
