### ISSUE TITLE
[12.0] sale_triple_discount import sale order error

### ISSUE THREAD

**Issue by rafamarpe** [OCA/sale-workflow#1103]
Hi!
When we import an order with its lines, the subtotals are not being calculated correctly. It is only correct in the first line, in the following ones the 2 and 3 discount are ignored.
It has been tested in the runbot.
Sales order SO029.
The error is always reproduced when imported.
Excel attachment
[import.xlsx](https://github.com/OCA/sale-workflow/files/4380297/import.xlsx)

**Comment by rousseldenis** [comment]
@SimoRubi @tafaRU Could you help with this ?

**Comment by SimoRubi** [comment]
Hi, yes I can look into it it when I have some spare time

**Comment by SimoRubi** [comment]
@rafamarpe I have imported your file in latest runbot v12 and seems to me that discounts are correct for all products:
![image](https://user-images.githubusercontent.com/32064796/90158326-2b9d1c80-dd8f-11ea-9d39-5577fa8218f3.png)
Can you confirm that the issue does no longer exist?

**Comment by SimoRubi** [comment]
@rousseldenis OP hasn't answered in a month and issue does not seem to be happening anymore, can this be closed?

**Comment by SimoRubi** [comment]
@OCA/crm-sales-marketing-maintainers can this be closed?

**Comment by SimoRubi** [comment]
@OCA/crm-sales-marketing-maintainers can this be closed?

**Comment by SimoRubi** [comment]
?
