### ISSUE TITLE
suggestion to integrate "sale_discount_display_amount" & "sale_fixed_discount"

### ISSUE THREAD

**Issue by mahmoudmk1** [OCA/sale-workflow#1106]
module: sale_discount_display_amount & sale_fixed_discount
version: 12.0
Hello Sir
I’d like to suggest to integrate these two modules sale_discount_display_amount & sale_fixed_discount
**Current behavior**
sale_discount_display_amount shows **only** the summation of percentage discount on lines
**Expected behavior**
sale_discount_display_amount shows also "sale_fixed_discount" or "Odoo default percentage discount "

**Comment by mehdi-ghezal** [comment]
It's mostly because of this line : https://github.com/OCA/sale-workflow/blob/13.0/sale_discount_display_amount/models/sale_order_line.py#L22 

When we set a fixed discount, it's the discount_fixed field that hold the discount and not the discount field.

**Comment by Rad0van** [comment]
+1 here. In this combination it actually doesn't work properly.
When % discount is applied, it is correct:
![image](https://user-images.githubusercontent.com/19169467/105489207-2daac600-5cb3-11eb-9cf7-421af21bca30.png)

But when fixed discount is applied, it is wrong:
![image](https://user-images.githubusercontent.com/19169467/105489463-8d08d600-5cb3-11eb-8076-67219e86d7c8.png)

@LoisRForgeFlow, @JordiBForgeFlow, @Cedric-Pigeon, @Abranes or @pedrobaeza any pointer on how to best fix this?
