### ISSUE TITLE
Installation error when i try to install this module.

### ISSUE THREAD

**Issue by Vignesh000** [OCA/sale-workflow#1116]
I already install sale_isolated_quotation for the sequence numbers. then I install this module for revisions sequence it can't install.

**Comment by bodedra** [comment]
For which version? :smile:

**Comment by Vignesh000** [comment]
odoo12 :(

**Comment by bodedra** [comment]
I have re-read your question and cannot able to understand. Can you update your question and provide clear information? And what do you mean by "this module"?

**Comment by Vignesh000** [comment]
sorry, "this module(sale_order_revisions)". 
**odoo server error**
 "duplicate key value violates unique constraint "sale_order_revision_unique"
DETAIL: Key (unrevisioned_name, revision_number, company_id)=(TTPL/QUO/075, 0, 1) already exists." this error came when i installed sale_order_revisions module.
