### ISSUE TITLE
[13.0][Question] sale_automatic_workflow_payment_mode

### ISSUE THREAD

**Issue by atchuthan** [OCA/sale-workflow#1118]
In one of our customer customization, we added a few informations to be sent via Register payment button, but the sale_automatic_workflow_payment_mode created the payment directly using a predefined values in https://github.com/OCA/sale-workflow/blob/12.0/sale_automatic_workflow_payment_mode/models/automatic_workflow_job.py#L43-L52

So, when migrating it to v13, we are planning to use the Register payment button and add the defined values as a default context and post the payment.  We are trying to reuse Odoo's existing code to create payment instead of using predefined create values and posting the payment directly.

Please share your suggestions and alternative options.

**Comment by atchuthan** [comment]
@lmignon @hugosantosred @florian-dacosta

**Comment by rousseldenis** [comment]
@atchuthan Some flows have been modified as Odoo base code is more reliable for payments. We rely on acquirer now to bind sale and workflow as you can see there : https://github.com/OCA/sale-workflow/pull/1016

Does this fullfill your requirements ?

**Comment by atchuthan** [comment]
yes, this could be an alternative.
