### ISSUE TITLE
Sale order line price history + Invoice

### ISSUE THREAD

**Issue by Zephyria77** [OCA/sale-workflow#1127]
Good morning, using this module I have think will be useful to add search history price also in the invoice line. Various company need to review price on sale order based on quantity effectively invoiced.
Thanks to all

**Comment by rousseldenis** [comment]
@ernestotejeda @murtuzasaleh What do you think of this ?

**Comment by pedrobaeza** [comment]
Well, that would be another different module and of course it can be interesting, but no funds nor customer requirement for now for that.
