### ISSUE TITLE
[12.0] Main branch is red on travis (sale_elaboration + sale_stock_secondary_unit).

### ISSUE THREAD

**Issue by rousseldenis** [OCA/sale-workflow#1146]
https://travis-ci.org/github/OCA/sale-workflow/jobs/687769282#L2337

Sale order in tests is created without company_id (not required), so the invoice creation raises as it takes the one on sale order (and is required).

Last good build on 24th of April, first raise on 13th of May. 

https://github.com/OCA/sale-workflow/blob/12.0/sale_elaboration/tests/test_sale_elaboration.py#L125

Didn't find any relevant changes in Odoo code.

**Comment by rousseldenis** [comment]
Sale elaboration test is fixed with #1147 

@pedrobaeza Could you fix sale_stock_secondary_unit as the last commit (direct on 12.0 branch without PR) is yours ? https://github.com/OCA/sale-workflow/commit/f36fe4e11f5fa6cd0a2b7392454ee13fa1f26ebc

**Comment by pedrobaeza** [comment]
Yes, I'm checking today and letting it green. If you want, I can switch also `sale_elaboration` to a better approach with `tests.Form` class.

**Comment by rousseldenis** [comment]
> Yes, I'm checking today and letting it green. If you want, I can switch also `sale_elaboration` to a better approach with `tests.Form` class.

Ok, if you want.

**Comment by pedrobaeza** [comment]
Fixed in 596aed2
