### ISSUE TITLE
[13.0]Request of quotation CONFIRM ORDER validate

### ISSUE THREAD

**Issue by anviz-github** [OCA/sale-workflow#1158]
<img width="1440" alt="Screen Shot 2020-06-04 at 12 55 32 PM" src="https://user-images.githubusercontent.com/54052406/83716637-07bcac80-a663-11ea-8e64-a6277315efd0.png">
When install sale_tier_validate,confirm the request of quotation want to validate.
Thank you!

**Comment by pedrobaeza** [comment]
`sale_tier_validation` is for sales, not for purchases.
