### ISSUE TITLE
Sale_order_lot_selection, constraints on lot

### ISSUE THREAD

**Issue by bealdav** [OCA/sale-workflow#1166]
Hi @eLBati @PCatinean,

I have a question about this module
There is a constraint which prevent to have 2 `stock.move.line` sharing the same lot and linked to a `sale.order`.

https://github.com/OCA/sale-workflow/blob/12.0/sale_order_lot_selection/models/sale.py#L39-L53

I would like to know the reason for which you introduced this constraint and if you really yet need in 12.0 (or only in old version). 
As said here https://github.com/OCA/sale-workflow/pull/1151 you may have use case required to have the same lot on several lines.

Please could you give me some informations ?

Thanks in advance

cc @manuelcalerosolis @sebastienbeau

**Comment by eLBati** [comment]
Hi @bealdav , sorry, I don't remember. I am not using this module at the moment, and never used in v12.
So I suggest to proceed in the way you think is best

**Comment by PCatinean** [comment]
Hi @bealdav, I checked and even used the blame feature but I can't remember/see any specific reason at this time on why that restriction was added (I just ported the module to the next version like this). I will ask some customers and collaborators to see if there's something I'm missing but as far as I know we don't require it specifically.

**Comment by bealdav** [comment]
@eLBati @PCatinean  Thanks for your replies.

We also noticed than sale_order_lot_selection prevent to confirm sale.order when there is no available stock with this lot. Odoo used alone doesn't prevent to confirm sale when there is no stock. It only alerts where you try to deliver with no stock.

I propose to remove the constraints preventing to confirm sale when lot is not available but to keep the constraints on delivery. The use case is when you define a lot for traceability (by sale.order.line) and the product is manufactured later with this lot.

If it cause a problem in your use cases I can make it configurable with a parameter or a method.

Let me know if any problem.

Thanks

**Comment by bealdav** [comment]
FYI @bodedra, I've seen you ported the module to 13.0. Are you ok for these changes ?
