### ISSUE TITLE
[12.0] Is there an addon that limits the payment_mode_id with respect to the payment_term_id in the sale_order?

### ISSUE THREAD

**Issue by victoralmau** [OCA/sale-workflow#1195]
We have a small addon that adds a many2many field payment_mode_id in the payment_term_id
The objective of this is to limit the payment_term that can be selected from the sale_orders.

Before creating a PR to add this addon, I would like to know if it exists, and if it does not exist, what name do you suggest for this addon.

Thank you very much.

**Comment by pedrobaeza** [comment]
I don't know any, but it should be planned as a base module with a mixin for being added to sale.order, account.invoice, purchase.order... so that you don't need to re-add the same logic/fields for each one (only little glue modules inheriting that mixin). It can go to OCA/bank-payment.

Anyway, not sure this is a common use case.

**Comment by HaraldPanten** [comment]
IMO you could think about a more standard and generic module improving this one that you have, making it more powerful and covering more use cases. The idea is not bad. For example:

1- Imagine something like "payment_term_rule" module.
2- This module allows users to set different limit/restrictions to payment terms. Some examples could be:

- limit a payment term depending on a partner: Imagine that you only want that your VIP partners can pay 90 days after invoice date and the rest of them have to pay 30 or maximum 60 days after invoice date.
- limit a payment term depending on the payment mode (as you need).
- limit a payment term depending on the total amount.
- limit a payment term depending on any product/product category from the SO lines.
- limit a payment term depending on a salesteam/salesperson
- ...

You should think as well, what would happen in the invoice, not only in the SO. I mean:

1- You limit a payment term depending on the payment mode. (SO).
2- You create a SO respecting this limitation/rule.
3- You create an invoice from the SO.
4- You edit the invoice and you select a "forbidden" payment term for the defined payment mode in the invoice.

Would that behaviour make sense? 🤔
Should the restriction be respected in the invoices as well? 
Could this restriction be ignored in the invoices, but only for some user roles?
...

I know that it's going to make you invest much more hours thinking/developing and testing but something more usable and more "OCA style" would cover more use cases and probably you'll find more people interested on it.

Don't get me wrong, that's only a suggestion, for sure 👍

**Comment by victoralmau** [comment]
Ok, thank you very much for your opinion.
I fully understand what you are saying and that the addon that is proposed as such does not make sense as it is so specific, but as you indicate something very general based on rules that could affect both sales and invoices (if configured), etc. prove useful.

I write it down as the correct solution (create this new rules-based addon) although due to the amount of work it would take I leave it pending and give priority to others.

Thank you very much.

**Comment by victoralmau** [comment]
On the other hand I respect the question that was posed I think it would not be a bad idea to add payment_term_ids (many2many) in the model: account.payment and add it in the account_payment_mode addon (https://github.com/OCA/bank-payment) and add a domain to filter on invoices and sale_orders through the addon: account_payment_sale. 

Do you think that this little suggested improvement to existing addons can be useful or is it a very strange use case?

**Comment by HaraldPanten** [comment]
I don't need it at the moment, but it might be interesting for other users
