### ISSUE TITLE
[12.0] Auto send mails with sale_automatic_workflow?

### ISSUE THREAD

**Issue by victoralmau** [OCA/sale-workflow#1199]
Hello,

I think the **sale_automatic_workflow** addon is very useful but I'm not sure if you can configure a mail process, that is, for each sale_automatic_workflow define a process like:

- Mail A> Filters for the custom sale_order (A)
- Mail A1> If Mail A has been sent and X is satisfied
- Mail A2> If Mail A has been sent and Y is satisfied
- Mail B> Custom sale_order filters (A)

Emails should be sent 1 time per sale_order.

Is this possible to do with the sale_automatic_workflow addon or some other? Is it planned as functionality in the future?

Thank you very much.

**Comment by pedrobaeza** [comment]
You can do it with `base_automation` defining an automated action when the sales order changes the state, but it can be also OK to add that feature in this module.

**Comment by victoralmau** [comment]
Ok, thank you very much, I think it serves what I am looking for although you should always keep in mind to update some field of the existing ones so that the same email is not sent (for example) constantly.
