### ISSUE TITLE
[13.0] sale_order_type: Entrysequence wrong when duplicatin existing sale-orders

### ISSUE THREAD

**Issue by rgl1234** [OCA/sale-workflow#1223]
Hi
We have created some different sale-order-types with different sequences. When creating a new SO, the correct sequence for the type is used according to the type-setup. But when we duplicate existing sale-orders, that have already chosen a specific type, another sequence coming from another type is chosen event thought the sequence on the SO is set correctly. So the result is, that we have an SO with type A and sequence coming from type B.....
Can someone reproduce this issue?
Thanks
René

**Comment by rousseldenis** [comment]
@pedrobaeza @grindtildeath As you worked recently on it

**Comment by pedrobaeza** [comment]
@rgl1234 is this reproducible on runbot?

**Comment by rgl1234** [comment]
> @rgl1234 is this reproducible on runbot?

How can I connect to OCA-modules on runbot?

**Comment by pedrobaeza** [comment]
Just click on the "Try me on runbot" badge on the top of the README. admin/admin

**Comment by rgl1234** [comment]
thanks...
I tried to reproduce it on runbot. Until now I was not able to do so....But what I can see is, that on runbot by default when I create a new SO the SO-type is filled in by default also when the type-field on the partner is empty. On our test-db when I create a new SO I have to choose the type-field manually, if it is not set on the partner.....
Where can I set the default-value for new SO? I could not found a configuration-value in ir.default on runbot.....maybe the difference is coming from there.....
René

**Comment by pedrobaeza** [comment]
I think you are not using latest code version, but an outdated one. Closing this meanwhile you figure out that.

**Comment by rgl1234** [comment]
ok...you are right, I will first have to update to the latest code....I will test it again then....

**Comment by rgl1234** [comment]
@pedrobaeza 
I just look into this issue with newest code and still have problems duplicating SO also on runbot. Now when I duplicat an SO of Type "A", the type on duplicated order is set back to "Normal Order" and the name of the SO is eet to "/". See screenshot.....I think there is realy something wrong here.....
![image](https://user-images.githubusercontent.com/11720329/94241630-2a761800-ff15-11ea-948c-ba7d31eb33cb.png)
