### ISSUE TITLE
[RFC] product categories more accessible from sales module.

### ISSUE THREAD

**Issue by HaraldPanten** [OCA/sale-workflow#1233]
IMHO, it doesn't make sense limiting product categories menu access, only from purchases or inventory modules. Users are often using sales + CRM + invoicing but not inventory or purchases.

Since product category menu is not accessible from sales module, wouldn't that make sense to create a module to make it more "accessible" from there? I know that it would be a "micro-module"...

Do you think that suggesting this idea directly to odoo/odoo would be better?

THX in advance for your opinions.

**Comment by rousseldenis** [comment]
> IMHO, it doesn't make sense limiting product categories menu access, only from purchases or inventory modules. Users are often using sales + CRM + invoicing but not inventory or purchases.
> 
> Since product category menu is not accessible from sales module, wouldn't that make sense to create a module to make it more "accessible" from there? I know that it would be a "micro-module"...
> 
> Do you think that suggesting this idea directly odoo/odoo would be better?
> 
> THX in advance for your opinions.

Indeed, that makes sense to have that menu point on Sale level.

Either, you can do a PR on odoo itself. If it is taken into account, it won't be merged in a stable version (only in master). So, for missing ones, you can do a PR on OCA/sale-workflow for that purpose.

**Comment by HaraldPanten** [comment]
> > IMHO, it doesn't make sense limiting product categories menu access, only from purchases or inventory modules. Users are often using sales + CRM + invoicing but not inventory or purchases.
> > Since product category menu is not accessible from sales module, wouldn't that make sense to create a module to make it more "accessible" from there? I know that it would be a "micro-module"...
> > Do you think that suggesting this idea directly odoo/odoo would be better?
> > THX in advance for your opinions.
> 
> Indeed, that makes sense to have that menu point on Sale level.
> 
> Either, you can do a PR on odoo itself. If it is taken into account, it won't be merged in a stable version (only in master). So, for missing ones, you can do a PR on OCA/sale-workflow for that purpose.

Thanks for your comments, Denis.

We'll create this [ADD] soon 👍

**Comment by HaraldPanten** [comment]
Closing, as PRs have been done for V12 and V13
