### ISSUE TITLE
[12.0] sale_order_line_price_history

### ISSUE THREAD

**Issue by RicardoNar** [OCA/sale-workflow#1243]
When I press the button "Set Price (Establecer Precio)" doesnt set the discount. Only set price without discount. 
is it correct?

**Comment by rousseldenis** [comment]
> When I press the button "Set Price (Establecer Precio)" doesnt set the discount. Only set price without discount.
> is it correct?

Hi @RicardoNar . I think you are mixing two modules. sale_order_line_price_history does not have a Set Price button...

**Comment by RicardoNar** [comment]
> > When I press the button "Set Price (Establecer Precio)" doesnt set the discount. Only set price without discount.
> > is it correct?
> 
> Hi @RicardoNar . I think you are mixing two modules. sale_order_line_price_history does not have a Set Price button...

Hi @rousseldenis , yes, this module has it in Odoo 12.

https://odoo-community.org/shop/product/sale-order-line-price-history-4704?search=sale_order_line_price_history

"5. You can also set the price of one of the price history lines in the sale order line. To do that, you have to open the price history line desired and click the smart button named Set price."
