### ISSUE TITLE
Builds failing on sale_sourced_by_line tests

### ISSUE THREAD

**Issue by joao-p-marques** [OCA/sale-workflow#1304]
Builds are failing when testing `sale_sourced_by_line`.

I am migrating another module and getting the error: https://travis-ci.com/github/OCA/sale-workflow/jobs/407124245#L1525

I have also seen that builds are failing for the same reason on different branches: https://travis-ci.com/github/OCA/sale-workflow/jobs/407234444#L1494

ping @acsonefho @saxomanu @MiquelRForgeFlow

TT25948

**Comment by rousseldenis** [comment]
I think this is due to https://github.com/odoo/odoo/commit/51b7960f7e30aab471bb846cb890efd95c7b2dcc#diff-7d271dc8cd91058e14e1677a1c6e17d155106fa88ccd0dce46ec8c345a38b91d

I'll check

**Comment by rousseldenis** [comment]
This one would fix it : https://github.com/OCA/sale-workflow/pull/1305
