### ISSUE TITLE
sale_type_id is not defined in sale.order

### ISSUE THREAD

**Issue by BT-jmontero** [OCA/sale-workflow#1315]
https://github.com/OCA/sale-workflow/blob/23caf26e3951b2abac172954854c24cfef356a82/sale_order_type/models/sale.py#L28

Shouldn't it be 

`
record.**type_id** = self.env["sale.order.type"].search([], limit=1)
`
?

**Comment by rousseldenis** [comment]
@pedrobaeza Could you fix this as you did the modifications there: https://github.com/OCA/sale-workflow/commit/8e40947084d9224a3ef7dd27a4fce0f2a9f26d0f#diff-3fd48516bef3a42070c960c3e63c5b5efa264e438f6f53a1fc669614483c8079R22

and add a test :smiley:

**Comment by pedrobaeza** [comment]
Thanks for noting. Fixed in 10aecb4

**Comment by pedrobaeza** [comment]
s/nothing/noting

hehe bad typo...
