### ISSUE TITLE
[RFC] Default sales incoterm place per partner

### ISSUE THREAD

**Issue by yostashiro** [OCA/sale-workflow#1320]
We have this module https://github.com/OCA/sale-workflow/tree/12.0/sale_order_incoterm_place now, and we'd like to have the place (together with the code) proposed based on the partner.

A question - which of the following would be a better option?
Option 1. Have the place field covered in https://github.com/OCA/sale-workflow/tree/12.0/sale_partner_incoterm
Option 2. Create a new module to only handle the place field

To me option 1 is better, albeit with extra dependency, because I don't know of a business situation where only the code (e.g. 'FCA') should be managed without a place.

**Comment by dreispt** [comment]
What would be the extra dependency?

**Comment by yostashiro** [comment]
> What would be the extra dependency?

@dreispt https://github.com/OCA/sale-workflow/tree/12.0/sale_order_incoterm_place

https://github.com/OCA/sale-workflow/tree/12.0/sale_partner_incoterm currently depends on just sale_stock. Option 1 assumes that sale_order_incoterm_place is added to the dependency list.
