### ISSUE TITLE
Secondary unit wrong calculation in sale order

### ISSUE THREAD

**Issue by jaferrer** [OCA/sale-workflow#1387]
module: sale_order_secondary_unit
version: 12.0

**Steps to reproduce**

- 1 Create a product with secondary unit (bag-100)

![image](https://user-images.githubusercontent.com/16543165/102758698-6b929280-4373-11eb-82f2-dda9c0017ffd.png)

- 2 Place a new Sale Order Quaotation and create a new order line using "Configure a Product" and set to (i.e.) 6 units to order

![image](https://user-images.githubusercontent.com/16543165/102759117-fb384100-4373-11eb-8233-7a650cafc568.png)

**Current behavior**

After placing a new order line with a product with secondary unit with "Configure a Product" the specified quantity is not correctly reflected and always gets the default secondary unit without further calculation. (In this case 100 units)

![image](https://user-images.githubusercontent.com/16543165/102759486-7ac61000-4374-11eb-8bd3-a05c4e9bd136.png)

**Expected behavior**

Quantity specified in "Configure a product" must be correctly calculated either multiplying entered quantity by secondary unit or,  at least,  passing entered valued as is.

Taking into account secondary unit

6 x bag-100 (600 units)

Passing quantity without taking care of secondary unit

6

https://user-images.githubusercontent.com/16543165/102760762-4fdcbb80-4376-11eb-898f-0a88ca8336fb.mp4

Regards,
Jose A. Ferrer

**Comment by pedrobaeza** [comment]
There's no support for the product configurator in this module.

**Comment by jaferrer** [comment]
Ok.

No additional info in module's  main page regarding its lack of that funcionality though.

**Comment by pedrobaeza** [comment]
No. Please add a pull request adding such information in the README.
