### ISSUE TITLE
[12.0] sale_triple_discount incorrect result

### ISSUE THREAD

**Issue by ioans73** [OCA/sale-workflow#1391]
When creating a line with 3 different discounts in a Sale Order:

Unit price: $150
Discount 1: 20%
Discount 2: 10%
Discount 3: 5%

We save and the subtotal is set to: $102.06

Now once we modify the value of Discount 2, setting it to 5% and saving the line, we can see that the field does not update, maintaining its initial value and therefore, the subtotal doesn't re-calculate either.

Testing was done on a Runbot instance.

Does anyone know anything about this issue?

![sale_triple_discount](https://user-images.githubusercontent.com/29223264/102866734-094f9580-4438-11eb-864e-ece8df0b14ac.gif)

**Comment by rousseldenis** [comment]
@eLBati @tafaRU @SimoRubi Could you help here ?

**Comment by SimoRubi** [comment]
There is some history about triple discount cache management but as far as I know, it is for v10: https://github.com/OCA/sale-workflow/issues/817.

I don't know/recall of any similar issue in v12 (until now).

**Comment by ioans73** [comment]
To solve the problem, at least temporarily, we've refactored some of the module's code.
Our clients haven't complained since we made these changes.
If you think it could be helpful, we can make a PR to propose the changes.

**Comment by SimoRubi** [comment]
If the module has an issue, sharing a fix is helpful for sure :) thanks!

**Comment by ioans73** [comment]
> If the module has an issue, sharing a fix is helpful for sure :) thanks!

PR done https://github.com/OCA/sale-workflow/pull/1410

**Comment by SimoRubi** [comment]
@ioans73 sorry to bother again, since this is now solved, can you close?
