### ISSUE TITLE
[10.01] bank-statement-reconcile dipendence

### ISSUE THREAD

**Issue by protontrigg3r** [OCA/sale-workflow#1409]
File `oca_dependencies.txt` contains `bank-statement-reconcile` but this dependence is not present in the OCA.

**Comment by pedrobaeza** [comment]
It was renamed to account-reconcile, but both should work without problems, as GitHub keeps a redirection from previous names.

**Comment by protontrigg3r** [comment]
Thanks. Searching for `bank-statement-reconcile` on GitHub produces no results, so it's not possible to know what to install.

**Comment by pedrobaeza** [comment]
Well, but this version is very old, so not being an error, doesn't qualify for a fix from usual maintainers. Though, if you want to have it fixed, please apply the corresponding PR.
