### ISSUE TITLE
[12.0] sale_fixed_discount - Wrong tax_amount displayed on reporting

### ISSUE THREAD

**Issue by MAG-Florian-Chevalier** [OCA/sale-workflow#1424]
Hello,

On sale order reports, the field tax_amount seems to be incorrect.
The tax amount is calculated on the undiscounted price.
Untaxed total and total are correct, and tax amount is only wrong on report.

Regards,

**Comment by rousseldenis** [comment]
@MAG-Florian-Chevalier Could you change description if it's related to sale_fixed_**discount**
