### ISSUE TITLE
[12.0] sale_order_lot_selection: failing tests

### ISSUE THREAD

**Issue by CarlosRoca13** [OCA/sale-workflow#1446]
The tests on travis version 12.0 are failing by sale_order_lot_selection module, here you have a link to last travis run https://travis-ci.com/github/OCA/sale-workflow/jobs/479997013#L2198

ping @PCatinean @bealdav

**Comment by chienandalu** [comment]
It's funny this didn't fail until now :thinking:

**Comment by pedrobaeza** [comment]
Fix in #1458
