### ISSUE TITLE
[12.0] sale_fixed_discount : discounts multiplied by quantity of products

### ISSUE THREAD

**Issue by vanderleiromera** [OCA/sale-workflow#1459]
![discount_fixed](https://user-images.githubusercontent.com/65144026/107536614-f6cc1f80-6b8f-11eb-884c-263b1d7a4051.png)

**Comment by rousseldenis** [comment]
@LoisRForgeFlow @JordiBForgeFlow Could you confirm the bug ?

@vanderleiromera Maybe you can write a test that reproduce the case you have here and make a PR, then we can find a fix.

**Comment by bodedra** [comment]
@rousseldenis I confirmed this bug at runbot http://3495083-12-0-c87d3c.runbot1-2.odoo-community.org/web?debug=1#id=25&action=464&model=sale.order&view_type=form&menu_id=293

**Comment by bodedra** [comment]
Related PR:

v12 - https://github.com/OCA/sale-workflow/pull/1443
v13 - https://github.com/OCA/sale-workflow/pull/1440

That PRs haven't resolved issue. I can reproduce same with it.
