### ISSUE TITLE
Sale Secondary Unit Of Measure not working with volume UOM

### ISSUE THREAD

**Issue by Moto017** [OCA/sale-workflow#1549]
Use case is to display number of containers. E.G. 55 gal drum = secondary UOM 1 drum
Calculations for **Stock Secondary Unit** accurately accounts for Secondary UOM.

1. Create product with default UOM gal
2. Create secondary UOM to gal and factor of 1.0
3. Create Sale Order for product with Secondary UOM 1.

**Expected**: 
- Secondary UOM 1 gal 
- Ordered Quantity 1 gal

**Result**: Defaults calculations to Liters and results in the below for rounding: 
- Secondary UOM 0.980 gal
- Ordered Quantity: 0.260 gal

**Comment by pedrobaeza** [comment]
If the introduced factor is 1.0, how do you expect that something is changed?

**Comment by Moto017** [comment]
It is the expectation that it is not suppose to change with the factor of 1.

Any factor can be introduced for secondary UOM, but is calculated incorrectly with calculations of the UOM reference factor.
In this case, Liters.

**Comment by pedrobaeza** [comment]
Uhm, I don't really get the problem. Where are you trying the modules? Maybe any extra module that is affecting?

**Comment by Moto017** [comment]
Tested in runbot with same results.

Our use case is to display quantity of 55 gal drums in stock and in sales with product UOM as gal.
If user inputs 1 55 gal drum, Ordered quantity calculates incorrectly to 14.530 gal instead of 55 gal

**Calculations factored**  factor = self.secondary_uom_id.factor * self.product_uom.factor
Secondary UOM factor 55 gal / Product UOM Factor 3.78541 gal (Bigger than reference UOM) = 14.530 gal

**Comment by pedrobaeza** [comment]
Sorry, but I still don't see it, as you write everything together and I don't know exactly what are the data. You put "user inputs 1 55 gal drum". What is 1? What is 55? Put some screenshots if not.

**Comment by Moto017** [comment]
Added Screenshots

**Secondary UOM Factor 55gal**
![image](https://user-images.githubusercontent.com/35890331/114206860-5f7e1100-9921-11eb-81b6-2d3d58cbf54d.png)

**Sale Order Line**
![image](https://user-images.githubusercontent.com/35890331/114207020-8b00fb80-9921-11eb-8f78-06b1a4d38138.png)

**Comment by pedrobaeza** [comment]
Why are you using 2 times `gal(s)` UoM both for main and secondary? That's the problem.

**Comment by Moto017** [comment]
Thanks for the suggestion.  Tested with any Secondary UOM, but does not affect the calculations.

Calculations are always defaulted to the Reference UOM Factor given self.secondary_uom_id.factor * self.product_uom.factor.  
Works as expected in all test cases with Unit(s) as the Reference UOM Factor is 1.0. 

I believe secondary UOM uom_id will need to be included to calculations in this case to achieve the results.  Will look into this further.

**Comment by Moto017** [comment]
Hi Pedro,

The problem occurs when the Product UOM is not the UOM Category Reference.

**self.secondary_uom_id.factor * self.product_uom.factor**
This calculation is backwards and results are only correct if the product UOM Category Reference (multiplied / divisible by 1)

I believe the calculations should be.
**self.secondary_uom_id.factor / self.product_uom.factor**
The secondary_uom_id would be for informational purposes only.

fix would also need to apply to purchasing secondary units

**Comment by pedrobaeza** [comment]
OK, thanks for checking the internals. @sergio-teruel what do you think about this?

**Comment by Moto017** [comment]
In the end, I got it working with the following factor calculation for our use case.  secondary_uom_id would need to be correlated to convert the uom to the requested product_uom

(self.secondary_uom_id.factor / self.secondary_uom_id.uom_id.factor) * self.product_uom.factor

It then requires UOM category restrictions as it then references the Category Reference UOM, which may defeat the purpose of this addon.  If the function is to allow different Category UOM, it may need to restrict to Category Reference UOM only.
