### ISSUE TITLE
Workflow to cancel invoices and payments

### ISSUE THREAD

**Issue by descuderosanchez** [OCA/sale-workflow#1560]
Hi,
Is there a module that automatically, when a paid invoice is canceled, automatically eliminates the accounting entry created by the payment?

When we cancel an invoice, we must go to the accounting entry to eliminate said entry and thus be able to make the modifications and re-record the payment, otherwise an accounting entry remains unassigned or reconciled.

**Comment by pedrobaeza** [comment]
Sorry, this is not an issue about any of the modules of this repository, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.
