### ISSUE TITLE
[14.0] Sale Order/Quotation revison problem

### ISSUE THREAD

**Issue by NICO-SOLUTIONS** [OCA/sale-workflow#1580]
Hey...
i am facing the following problem:
When i use the sale_order_revision module (in combo with base_revision) and want to revise a quote, it will not add a revision number to the base number of the quotation. Instead it jumps to the next sequenced base number.

Adiitional informations:
- I use the module sale_quotation_number as well, to separate quotations from orders.
- My sequence code prefix for quotations is "SQ/%(year)s/" and for orders "SO/%(year)s/"

All the best

**Comment by kittiu** [comment]
Can you describe in more detail? I.e., with replication steps or pictures or videos will help.

**Comment by NICO-SOLUTIONS** [comment]
1st: For some reasons, the setting for the enumartion was unchecked. Checking this leads now to the following behaviour...
When i revise now a quotation, it falls back to the sequence code of the orders ("SO" instead of "SQ"). 
No title is added to the quote, as it expects a "SQ"? 
I think due to the separation of quotes and order by "sale_quotation_number".

More details later...

**Comment by NICO-SOLUTIONS** [comment]
Ok is did some further tests... 
In General: prefix is always added with "/%(year)s" and the number of digits is 5. Now my observations:

**sales_quotation_number installed**
Use same enumeration checked:
- create quote, Tilte „SO/2021/00001“
- mark as send 
![1](https://user-images.githubusercontent.com/74965194/117649564-f5f75980-b18f-11eb-8462-451f3be54db4.png)
- revise new quote
- No title or reference is set!
![2](https://user-images.githubusercontent.com/74965194/117649657-10c9ce00-b190-11eb-8503-144c30d46365.png)
- Revisions is showing the reference (SO/2021/00001)
![3](https://user-images.githubusercontent.com/74965194/117649714-24753480-b190-11eb-99b7-8ab49d39502b.png)
- mark as send
- Another Revision shows the same behavior referencing the first revision in rev-list
![4](https://user-images.githubusercontent.com/74965194/117649887-56869680-b190-11eb-952e-e60ef1d0b505.png)

Use same enumeration unchecked:
- create quote, Tilte „SQ/2021/00001“
- mark as send 
![5](https://user-images.githubusercontent.com/74965194/117650033-8170ea80-b190-11eb-92fd-1a5908efcefa.png)
- revise new quote
- Title or reference given by increment of  the sequence number to "SQ/2021/00002", no revision attached
![6](https://user-images.githubusercontent.com/74965194/117650206-b8df9700-b190-11eb-915f-8027f1dbb18d.png)
- Revisions is showing the reference (SQ/2021/00001)
![7](https://user-images.githubusercontent.com/74965194/117650330-dd3b7380-b190-11eb-930a-a5bcc3100b0e.png)
- mark as send 
- Another Revision shows the same behavior referencing the first revision in rev-list
![8](https://user-images.githubusercontent.com/74965194/117650404-f2180700-b190-11eb-9158-a9d0a989e722.png)


**sales_quotation_number uninstalled**
- create quote, Tilte „SO/2021/00001“
- mark as send
![9](https://user-images.githubusercontent.com/74965194/117650521-1a076a80-b191-11eb-942b-684ded310b02.png)
- revise new quote
- Revision code is attached to the Ref.,Tilte „SO/2021/00001-01“
![10](https://user-images.githubusercontent.com/74965194/117650596-33101b80-b191-11eb-8594-e1754a84321b.png)
- Revisions showing the reference SO/2021/00001
![11](https://user-images.githubusercontent.com/74965194/117650647-44592800-b191-11eb-9666-62820f779e27.png)
- mark as send
- Another Revision shows the same behavior referencing the first revision in rev-list 
![12](https://user-images.githubusercontent.com/74965194/117650723-5935bb80-b191-11eb-972c-3b8ea2718ced.png)

So my conclusion ist, that using sales_quotation_number does not work with sale_order_revision up to now. For me the separation of quotes and orders is more important. But it would be awesome to have to  sale_order_revision working as well with that.

Hope this helps
Cheerio
Nils

**Comment by NICO-SOLUTIONS** [comment]
Hey @kittiu 
hopefully i won´t put to much parameters at the same time now.
I did some further test, in addition with the "sale_isolated_quotation" module which seem to be a nice feature as well.
I just want to make sure, that i do follow the intended use of it. Please give me a note, if that´s not the case.

While checking the "sale_isolated_quotation" module, i was not able to send the quotations directly from the quote view. When i mark a quote as sent in the quote view, it is not possible to convert it anymore. The only option (without marking the quote as sent) is to convert it to a sales order. And that needs to be confirmed again (why is there a difference between convert and confirm?). I think converting a quote to an order, should be handled like a confirmation of a Quote directly to an order. As the conversion of a quote is creating a sale order that needs to be confirmed again (because the sale order is still handled like a quote before confirming it), the separation does not make any sense to me this way. In addition, from my point of view a revision of a sales order is not necessary. 

I think it would be great to have all 3 module working together. I know this will be some work and i would like to provide my input to this.

From my point of view, the possibilities with the modules "sales_quotation_number" (for using different prefix/enumerations), "sale_order_revision" (for revising a quote, maybe this should be named "sale_quotation_revision") and "sale_isolated_quotation" (for separating the quotes from sale orders in different views) ideally should look like the following...

- create a quotation (only displayed in the quotation view with different sequence code prefix, e.g. "SQ") with the ability to send it from there, which is separeted from sale orders view. The possibility to create another quote revision in the quotation view would be awesome. 
- convert/confirm the quote (e.g. "SQ/2021/00003-02") to a sales order (e.g. "S0/2021/00001") and have the sales order only in the order view with the quote as reference, keeping the quote in the quote view with the sale order as reference.

Would it be helpful to post some more pictures? Of course I would be willing to provide them.

If you think, that i am doing something wrong, i would appreciate an appropriate hint.

Alll the best

**Comment by kittiu** [comment]
Thank you for the feedback.

But just to let you know that, while we will try to make things works
together, some module really can't be for some good reason. And normally,
we will have a flag in manifest that, the 2 modules shouldn't be together.

While module sale_isolated_quoation is a need for some organization, but
this is one kind of module that can't fit with others well, mainly because
it breaks flow of standard odoo.

But we will take closer look, for what can be fit based on your finding.
Thanks again, for the feedback.

**Comment by NICO-SOLUTIONS** [comment]
You are very welcome...

Concerning breaking the standard work flow of odoo. Thats what i thought... A change can entail a slew of changes. 
beside your efforts to make things work, i will try to get into more detailed understanding of these coherences. Already on the track ;P

Thanks for your response!
