### ISSUE TITLE
[12.0] sale_order_min error in merge

### ISSUE THREAD

**Issue by igallart** [OCA/sale-workflow#1606]
Hello, in branch 12.0 sale_order_min_qty has corrupt.

View the module in branch 12, only has two files!

**Comment by legalsylvain** [comment]
indeed. could you make a PR to remove that files ? 
thanks.

**Comment by ValentinVinagre** [comment]
@rousseldenis

**Comment by rousseldenis** [comment]
> @rousseldenis

Ok, a too fast merge for migration PR. I will fix that

**Comment by rousseldenis** [comment]
@igallart The module has been renamed too sale_restricted_qty

**Comment by rousseldenis** [comment]
Fix there #1640
