### ISSUE TITLE
[13] sale_order_invoice_amount incorrect values

### ISSUE THREAD

**Issue by sergioeix** [OCA/sale-workflow#1609]
When invoices are grouped by customer the invoiced and uninvoiced amount are not well calculated.
Steps to reproduce:
1 make 2 orders with same customer confirm and validate delivery
2 make the invoice grouping this 2 orders 
3 check uninvoiced and invoiced fields on the orders, totals are taken from the same invoice and are wrong
I mean if order A is 100 and order b 200 then grouped invoice AB is 300 then invoice amount on order A is 300 and invoice amount on order b is 300, thats the issue.

**Comment by DS-Landoo** [comment]
Hello!

Are there any news regarding this? We have the same issue in V14 and would like to know if its going to be solved at some point.

Regards!
