### ISSUE TITLE
[13.0] sale_partner_delivery_window: Error on tests

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/sale-workflow#1621]
This module is provoking an error on current CI:

https://travis-ci.com/github/OCA/sale-workflow/jobs/516775218#L2177

Can you please check @simahawk @sebalix @grindtildeath ?

**Comment by simahawk** [comment]
It seems another error happens before on sale_by_packaging https://travis-ci.com/github/OCA/sale-workflow/jobs/516775218#L2129

**Comment by pedrobaeza** [comment]
Thanks for the quick reaction.

**Comment by grindtildeath** [comment]
Issue should be fixed with this PR: https://github.com/OCA/stock-logistics-workflow/pull/862
