### ISSUE TITLE
Procurement groups and "back 2 draft" incompatible

### ISSUE THREAD

**Issue by JavierIniesta** [OCA/sale-workflow#165]
If you try to re-draft a sales order, it will raise the following error:
![selection_032](https://cloud.githubusercontent.com/assets/11073758/8008993/f0b804d8-0ba5-11e5-885d-e8064cddfc93.png)

No group has permission to delete objects procurement.order:
![selection_031](https://cloud.githubusercontent.com/assets/11073758/8009084/7756fe86-0ba6-11e5-9c3d-b7d8a7ea0c55.png)

sale_order_back2draft/models/sale_order.py, line 21:

``` python
order.procurement_group_id.unlink()
```

**Comment by pedrobaeza** [comment]
This should be now fixed in https://github.com/OCA/sale-workflow/commit/d0a23572f49ef5ca77283a62e30c5ccabdb1f018
