### ISSUE TITLE
Pack management

### ISSUE THREAD

**Issue by sebastienbeau** [OCA/sale-workflow#170]
# Pack Managment

A long time ago I was using product_pack (https://github.com/ingadhoc/odoo-addons/tree/8.0/product_pack) from Nan-tic, and now on V8 I have a customer that need to use Pack.
I can reuse this module but I think this module have some duplicated concept with BOM, and maybe it's an opportunity to improve it.

For now the BOM already support in some way the PACK, indeed you can already create a "phantom" BOM and in this case when you add a product into the sale order it will be explode in the picking. But some time you need to explode it already directly in the sale order level and in this case the BOM can not support this behavior.

I think it can be interesting to give the possibility to explode the BOM directly in the sale order.

So I propose to create two module "sale_pack", "sale_bom_availability"
# sale_pack

This module replace product_pack  and use the BOM instead (but do not support stock computation)
- To improve the UI we can add a boolean "pack" on the product and if you tick that option you have directly a new tab that show you the Bom line directly from the product.
- You have an option if you want to have the price on the "parent" or "on the child" ("components_price" / "fixed_price" like in product_pack)
- If a service product is added on a sale order with that option than a product of the line are directly added in the sale order (same behaviour as product_pack)
# sale_bom_availability

This module will compute the quantity of product you can produce, using normal BOM, phatom BOM or PACK => totaly generic !
# More

We will also propose a module call "sale_option" that give you the possibility to configure the product you sold based on optional bom line and also sale_prodlot that give the posibility to track a product directly from the sale order.
# What do you think?

**Comment by jgrandguillaume** [comment]
Hi,

sale_bom_availability seems a duplicate of https://github.com/OCA/product-kitting/tree/8.0/__unported__/bom_stock

sale_pack seems dupplicate (partial dupplicate) of  : https://github.com/OCA/product-kitting/tree/8.0/__unported__/sale_bom_split

I also think that this should be moved under the product_kitting project as this one is supposed to deal with that kind of things, what do you think ?

Otherwise, the suggested improvements, I think are good :)

Regards,

Joël

**Comment by sebastienbeau** [comment]
Great bom_stock is indeed exactly what I mean with sale_bom_availability (OCA is so efficient !)

Regarding sale_bom_split, I will take a look on it (just to understand it), but it will not fit with my need. Indeed I need to have the explode directly in the sale order, like we did when we import bundle ligne from magento.

Thanks for you're feedback. We will propose the sale_option and sale_prodlot into product_kitting

**Comment by pedrobaeza** [comment]
If you only want to show in the sale order report the components, you can modify the qweb report to include the BoM on it.

**Comment by OSguard** [comment]
sale_bom_split is not needed in v8 as odoo core already support it

**Comment by anajuaristi** [comment]
Hello:
Trying to test modules on runbot I can not find a built where I can go into
https://runbot.odoo-community.org/runbot/repo/github-com-oca-product-kitting-136

Could you please help me on that? What should I do to have a database to launch and make test?

Sorry if this is a silly newbie question but usually when I go into runbot most of builts use to show a blue icon with small door that I push to go into and work.
This time this icon is missing. If I push force build, it stays "pending" so nothing happens.

Thank you!

**Comment by jgrandguillaume** [comment]
@anajuaristi Seems this project not activated on runbot, can you send a request to support@odoo-community.org please ?
