### ISSUE TITLE
[12.0] sale_discount_display_amount, missing strings in weblate

### ISSUE THREAD

**Issue by GSLabIt** [OCA/sale-workflow#1702]
Hi there,

it seems some strings are missing in weblate

https://github.com/OCA/sale-workflow/blob/d824748643451e56d86665a60741c7e5b8579732/sale_discount_display_amount/i18n/it.po#L21-L27

weblate:

https://translation.odoo-community.org/projects/sale-workflow-12-0/sale-workflow-12-0-sale_discount_display_amount/

Is there any issue?

**Comment by GSLabIt** [comment]
@sbidoul could you please double check?

**Comment by GSLabIt** [comment]
@pedrobaeza sorry for bothering, any chance to have a look at weblate?

**Comment by pedrobaeza** [comment]
I can't say about that.

**Comment by GSLabIt** [comment]
> I can't say about that.

Any hint on how to "force" update on weblate?

**Comment by sbidoul** [comment]
I don't understand this. It is different from the usual problem where the .po and .pot are not merge. Here weblate is not picking up the new strings from the .pot (maybe it's because its is the same text, with or without the `<strong>` tag ? I deleted the component in weblate. Can you check tomorrow if it is back and things improved ?

**Comment by GSLabIt** [comment]
@francesco-ooops can u double check tomorrow?

**Comment by francesco-ooops** [comment]
> I don't understand this. It is different from the usual problem where the .po and .pot are not merge. Here weblate is not picking up the new strings from the .pot (maybe it's because its is the same text, with or without the `\<strong\>` tag ? I deleted the component in weblate. Can you check tomorrow if it is back and things improved ?

Seems ok now! you can close

**Comment by GSLabIt** [comment]
@sbidoul fixed, thx
