### ISSUE TITLE
V14 sale_order_line_price_historic

### ISSUE THREAD

**Issue by vanderperre** [OCA/sale-workflow#1709]
problem with widget.
Retraçage :
Error: QWeb2: Template 'sale_order_line_price_history.price_history_widget' not found
exception@http://dev.local/web/content/180-ffa4deb/web.assets_common.js:4384:7
_render@http://dev.local/web/content/180-ffa4deb/web.assets_common.js:4429:103
render@http://dev.local/web/content/180-ffa4deb/web.assets_common.js:4425:151
renderElement@http://dev.local/web/content/180-ffa4deb/web.assets_common.js:4940:775
_widgetRenderAndInsert/<@http://dev.local/web/content/180-ffa4deb/web.assets_common.js:4950:6

**Comment by pedrobaeza** [comment]
Are you able to reproduce it on OCA runbot?

**Comment by vanderperre** [comment]
Perhaps i had a problem with my asssets frontend, it is not due to your module. 
Sorry and Thks.
