### ISSUE TITLE
Error while importing module 'sale_order_line_price_history'.

### ISSUE THREAD

**Issue by naved4all** [OCA/sale-workflow#1751]
module: sale_order_line_price_history
version: 14.0

**Steps to reproduce**
- Error while importing the module
- 
**Current behavior**

<html>
<body>

Error while importing module 'sale_order_line_price_history'.   Module loading sale_order_line_price_history failed: file /tmp/tmp8eu66f99/sale_order_line_price_history/security/ir.model.access.csv could not be processed:  No matching record found for external id 'model_sale_order_line_price_history' in field 'Model' No matching record found for external id 'model_sale_order_line_price_history_line' in field 'Model' Missing required value for the field 'Model' (model_id) Missing required value for the field 'Model' (model_id)   Make sure those modules are installed and try again.
--

</body>
</html>

**Expected behavior**

**Comment by pedrobaeza** [comment]
You need to add the module to the addons path. Importing modules is only for data modules (like themes).

Closing as no issue, but incorrect deployment.

**Comment by naved4all** [comment]
Thank you for your prompt reply.


Best Regards,



*Naved Ahmed *
