### ISSUE TITLE
Don´t see the Settings > Technical > Parameters > Global Discounts after install on V13

### ISSUE THREAD

**Issue by alexandrol** [OCA/sale-workflow#1754]
module: sale_global_discount
version: 13.0

**Steps to reproduce**
Download the module
Install the module
Restart the odoo instance
Go to Settings > Technical > Parameters

**Current behavior**
The Global Discounts is not there

**Expected behavior**
See the Global Discounts to be able to configure the discounts.

**Comment by pedrobaeza** [comment]
I have added the following clarification: `To be able to handle global discounts, you need first to give to your user the "Manage Global Discounts" permission.`

**Comment by alexandrol** [comment]
Thanks,

Now after configuring the permission, as you indicate, I can effectively access to create the discount, from Settings> Technical> Parameters> Global Discounts, and also from the Client configuration. But I can't apply the discount

**Steps to reproduce**
Install the module
Activate "Manage Global Discounts" permission on user
Create a Discount for Sale
Assign the discount to a Customer
Create a new sale order
    1) To the customer to whom the discount was assigned
    2) To another client

**Current behavior**
    1) I do not see any option to apply the created discount
    2) I do not see any option to apply the created discount

**Comment by pedrobaeza** [comment]
I'm able to see them:

![Selección_013](https://user-images.githubusercontent.com/7165771/139292547-f040875b-2243-4553-9f11-a742bf0edea1.png)

**Comment by alexandrol** [comment]
Yes, it appears well in the assignment of the customer discount, where I do not see it is during the creation of the Sale Order

![Screenshot from 2021-10-28 12-07-44](https://user-images.githubusercontent.com/16417374/139294103-00752d3e-6927-4f5c-89f1-a87be5571dc1.png)
r

**Comment by pedrobaeza** [comment]
I do:
![Selección_014](https://user-images.githubusercontent.com/7165771/139296086-e7b5c668-5490-4836-bd34-c2e7f90d9123.png)

**Comment by alexandrol** [comment]
And, are you in Version 13?

**Comment by pedrobaeza** [comment]
Yes, http://3511799-13-0-be2c0c.runbot2-3.odoo-community.org/web (admin/admin)

**Comment by alexandrol** [comment]
Thanks for the access.

The version I have behaves very differently, but I managed to see that the module does not meet a requirement, I see that the global discount is copied as an individual discount for each line.
In my case, I am interested in having independent discounts per line, and a global discount on the sum of the lines.

Once again, thank you very much,
