### ISSUE TITLE
[RFC] sale_order_partner_restrict -  Only allow to enter sales orders for companies or individual, not their associated contacts

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/sale-workflow#1811]
Currently you can create sales orders where the customer is a contact person, invoice address, etc.

However sometimes companies prefer to make sure that the order is only entered for the main company, in B2B, or the individual person in B2C.

The module 'sale_order_partner_restrict' would allow you to choose what level of restriction you'd like to apply when selecting from the list of customers.

This configuration would be available in Sales / Configuration / Settings, and the options available would be:

* All partners (default)
* Only parent accounts (no contacts)
* Parent accounts and contact persons

cc @ForgeFlow

**Comment by pedrobaeza** [comment]
Maybe this should be an extra option on the existing module: https://github.com/OCA/sale-workflow/tree/13.0/sale_partner_selectable_option

**Comment by JordiBForgeFlow** [comment]
@pedrobaeza good point

**Comment by HaraldPanten** [comment]
We've had similar requests from our customers. In POs too.

That should be restricted only for `partner_id` field. I'm not against Pedro's suggestion.

👍

**Comment by OriolVForgeFlow** [comment]
The existing module sale_partner_selectable_option doesn't make this option company dependent and the feature we want to add makes more sense if it does. We think that we should do a separate module to add that functionality as we are just adding a filter. What do you think?
@pedrobaeza @JordiMForgeFlow

**Comment by pedrobaeza** [comment]
Are you going to share contacts across companies?

**Comment by pedrobaeza** [comment]
Anyways, the extra option may work per company the same, through a field in `res.company`, but I don't want you to push to pack it in existing module. You can put another module for sure, and more if the scope starts to diverge too much.

**Comment by JordiMForgeFlow** [comment]
> The existing module sale_partner_selectable_option doesn't make this option company dependent and the feature we want to add makes more sense if it does. We think that we should do a separate module to add that functionality as we are just adding a filter. What do you think?
> @pedrobaeza @JordiMForgeFlow 

I agree, it would make more sense perhaps if the partner field was instead a property.

Nevertheless, it also seems to me that the sale_partner_selectable_option is more aimed at allowing manual flexibility on flagging the partners that should not be able to have orders, rather than to be used under a general setting.

**Comment by pedrobaeza** [comment]
OK, so go ahead with your module to complement these options.

**Comment by OriolVForgeFlow** [comment]
Module "sale_order_partner_restrict" added! PR: https://github.com/OCA/sale-workflow/pull/1826
