### ISSUE TITLE
[BUG][14.0] sale_product_set: Removing products in "Add Set" wizard doesn't do anything

### ISSUE THREAD

**Issue by gaikaz** [OCA/sale-workflow#1817]
## Module
sale_product_set

## Describe the bug
Removing products in "Add Set" wizard doesn't do anything.
Even though intuitively it seems that this table is sort of a "staging" place before adding the products to the Sale Order. 

## To Reproduce
**Affected versions**: 14.0 (probably earlier too)

Steps to reproduce the behavior (doable on OCA Runbot):
1. On DB with demo data
2. Start creating new Sale Order
3. Click "Add Set" (opens the wizard)
4. Select demo set "i5 computer offer" (3 products show up)
5. Remove one product from the wizard window, so that 2 remain
6. Submit the wizard so it adds the products to the Sale Order
7. !! All 3 initial set products get added, so the removed one was re-added

**Expected behavior**
Set should have added only 2 products to the Sale Order Lines instead of the whole set.

**Additional context**

https://user-images.githubusercontent.com/17097810/145581157-b4067fbb-d4c8-490b-8540-0515425be851.mp4

**Comment by legalsylvain** [comment]
Hi. this seems the expected behaviour for "set", don't you think. i better see the unpossiblity to remove product in the wizard, don't you think ?

**Comment by gaikaz** [comment]
Hi. Our project managers and couple of clients that use this module really thought that my described behavior is what should happen. It just seems this way intuitively.
But I do agree, that this is sort of a UI/UX issue if that was never the intention. Those x'es shouldn't be there if they don't even do anything.
Although, I'm pretty sure they are added explicitly, so I would guess that some versions ago, they did work?

**Comment by pedrobaeza** [comment]
For improving the UX, such list can be readonly.

**Comment by rousseldenis** [comment]
> For improving the UX, such list can be readonly.

Yes, but in a way, maybe with a configuration option/group to let it flexible.

**Comment by gaikaz** [comment]
We probably could make the X'es work instead of removing them. I honestly would prefer that as it would come in handy.

**Comment by Mantux11** [comment]
I'm working on this bug. I'll make a PR soon.
