### ISSUE TITLE
sale_order_revision error on "Confirm Sale"

### ISSUE THREAD

**Issue by thomaspaulb** [OCA/sale-workflow#184]
When you 
- Cancel a quotation
- Create a new copy of Quotation
- Confirm Sale

It says "You cannot confirm a sales order which has no line."

But many lines are there.
I will investigate further, just wish to know if other people have had this problem.

**Comment by thomaspaulb** [comment]
See pull request #186

**Comment by rafaelbn** [comment]
Hi, I thinks this issue can be closed as exists PR. @antiflu could you close issue? Thanks
