### ISSUE TITLE
To save the sale order makes to lost the manually asigned sale order type.

### ISSUE THREAD

**Issue by anajuaristi** [OCA/sale-workflow#1852]
To save the sale order makes to lost the manually asigned sale order type.

## Module
sale_order_type

## Describe the bug
Onchange partner_id on sale_order, assigns sale_order_type and calculates the number according to sale_order_type_secuence.
That's correct and right

Then.. change manually the sale order type on sale order --> the secuence is recalculated and everything seems Ok. 
But... save the sale order, the system is not respecting the change and the sale_order_type is changed, copying the one assigned on customer again. 
Now.. as the type is not correct, go and change again to set the correct one --> system recalculates the secuence. So the correct number is lost.
Expected behavior:
   Writing the sale order should not recalculate, nor the type, nor the secuence on it as it's correctly assigned on the onchange of sale_order_type before saving it.

## To Reproduce
**Affected versions**: Tested in V14

1. create a sale_order
2. change the sale order type on it
3. save --> the sale order type is lost. It's assigned the one that is assigned on partner.

**Expected behavior**
Writing the sale order should not recalculate, nor the type, nor the secuence on it as it's correctly assigned on the onchange of sale_order_type before saving it.

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by rafaelbn** [comment]
Ping @BT-cserra @newtratip ! Thank you! 😄
