### ISSUE TITLE
[14.0] sale_commitment_date_mandatory issue

### ISSUE THREAD

**Issue by damdam-s** [OCA/sale-workflow#1901]
Hello,

After some tests, there is an issue with the module sale_commitment_date_mandatory.
It's working pretty well when you create and confirm the sale order the same day or when the commitment date is enough far away.

This case is not covered and can lead to issues:

- security_lead is 1 day
- a SO is created today, as of 2021-10-14, commitment date is 2021-10-15
- the SO is confirmed 1 week later : 2021-10-21
- the picking will still have 2021-10-14 as a scheduled date

2 propositions here to discuss:

1. remove this "alpha" module from the repo
2. keep it but edit the "known bugs" section to mention the failing case

What do you think?

**Comment by mmequignon** [comment]
Could you please create a draft pr with a test that reproduces this error, and link it in the description ?
Thanks for your feedback ! :heart:

**Comment by jcoux** [comment]
@damdam-s @mmequignon 
PR to remove this module: https://github.com/OCA/sale-workflow/pull/1950

**Comment by sebalix** [comment]
I agree, making the `commitment_date` required is breaking tests of other addons in this repository (like here: https://app.travis-ci.com/github/OCA/sale-workflow/jobs/565374862). We should have be an option to enable in the sale configuration panel so we can enable it only for its own tests without disturbing other addons.

**Comment by sebalix** [comment]
I mitigate the issue this addon bring regarding Travis in this PR: https://github.com/OCA/sale-workflow/pull/1969
