### ISSUE TITLE
[14.0] sale_product_set: Travis is red on 14.0 branch

### ISSUE THREAD

**Issue by rousseldenis** [OCA/sale-workflow#1947]
Due to cherry-pick https://github.com/OCA/sale-workflow/commit/4766ba7a176231bfd96a8692b5dd1633fc62b963

@pedrobaeza @victoralmau Could you please fix that ?

**Comment by pedrobaeza** [comment]
As said, the problem has arisen on such commit, but it's not due to it. It's another module:

https://app.travis-ci.com/github/OCA/sale-workflow/jobs/563225847#L3450

sale_pricelist_from_commitment_date

Have you even checked the link I put?

**Comment by pedrobaeza** [comment]
I think the fix is coming in #1755

**Comment by rousseldenis** [comment]
Mmmh, just tested with an odoo last version and it seems more that one. Curently looking for culprit commit.

**Comment by rousseldenis** [comment]
That's the culprit: https://github.com/odoo/odoo/commit/86febae278f08864e83017d43f6aa9d67165d664
