### ISSUE TITLE
[13] sale_order_line_chained_move duplicate field

### ISSUE THREAD

**Issue by PedroInfo13** [OCA/sale-workflow#1974]
Hello @rousseldenis 

There is a duplicate field.
You create field related_sale_line_id on module stock.move. But in this module have a field sale_line_id.

I don't know why you do this.

I apreciate if you could explain it to me.

Thanks

**Comment by rousseldenis** [comment]
> Hello @rousseldenis
> 
> There is a duplicate field. You create field related_sale_line_id on module stock.move. But in this module have a field sale_line_id.
> 
> I don't know why you do this.
> 
> I apreciate if you could explain it to me.
> 
> Thanks

In Odoo, indeed there is a sale_line_id. But this is filled in only with the move from out > Customers (the one generated at sale confirmation).

But in case of several operations (two or three steps delivery), the sale_line_id is not filled in.

This module allows to have the full chain of moves generated through the original move with the sale line reference.

I hope this is clear :smiley:

**Comment by rousseldenis** [comment]
Note: I didn't want to reuse the sale_line_id field as it should break other processes.

**Comment by elvise** [comment]
> > Hello @rousseldenis
> > There is a duplicate field. You create field related_sale_line_id on module stock.move. But in this module have a field sale_line_id.
> > I don't know why you do this.
> > I apreciate if you could explain it to me.
> > Thanks
> 
> In Odoo, indeed there is a sale_line_id. But this is filled in only with the move from out > Customers (the one generated at sale confirmation).
> 
> But in case of several operations (two or three steps delivery), the sale_line_id is not filled in.
> 
> This module allows to have the full chain of moves generated through the original move with the sale line reference.
> 
> I hope this is clear 😃


Hey @rousseldenis  !

As i understood this module mantain the same lines from SO to all chained moves
If it's correct then looks it doesen't work.

I'm testing it in the runbot v14, please che this video:
https://drive.google.com/file/d/1KNsdpCzH8jm7L5S3m00AAm4Q56Yt76h5/view

Please let me know if i'm doing wrong something
Thanks for patience.

**Comment by sbouillon** [comment]
> > > Hello @rousseldenis
> > > There is a duplicate field. You create field related_sale_line_id on module stock.move. But in this module have a field sale_line_id.
> > > I don't know why you do this.
> > > I apreciate if you could explain it to me.
> > > Thanks
> > 
> > 
> > In Odoo, indeed there is a sale_line_id. But this is filled in only with the move from out > Customers (the one generated at sale confirmation).
> > But in case of several operations (two or three steps delivery), the sale_line_id is not filled in.
> > This module allows to have the full chain of moves generated through the original move with the sale line reference.
> > I hope this is clear 😃
> 
> Hey @rousseldenis !
> 
> As i understood this module mantain the same lines from SO to all chained moves If it's correct then looks it doesen't work.
> 
> I'm testing it in the runbot v14, please che this video: https://drive.google.com/file/d/1KNsdpCzH8jm7L5S3m00AAm4Q56Yt76h5/view
> 
> Please let me know if i'm doing wrong something Thanks for patience.

This works in Odoo 13, 14, 15 and 16. 

The intent of the module is to record the sale_line_id on the stock.move model. There are no views included in this module so the screen recording doesn't help much but it's definitely recording the sale_line_id on each move line.

![image](https://github.com/OCA/sale-workflow/assets/37988748/e6e48819-7ed9-4f22-ba94-4aee333ba726)
