### ISSUE TITLE
What is "sale-workflow" and "crm" projects scope?

### ISSUE THREAD

**Issue by dreispt** [OCA/sale-workflow#2]
I feel that it's necessary to agree on a scope for these closely related projects.
Since there now also a [CRM project](https://github.com/OCA/crm), how do we now where a module fits?

In my opinion, the frontier is Invoicing and order fulfilment:
- All features that go up to the point where you send a Quotation to a customer are CRM related.
- Features related to what happens from the Sales Order (Quotation won) onward should be Sales related.

Thoughts?

**Comment by eLBati** [comment]
I was assuming an approach linked to the odoo modules: if a module deals with sale\* modules, I would put it within the sale-workflow project; if it deals with crm\* modules, I would put it within crm

**Comment by dreispt** [comment]
@elBati that's a good rule of thumb, but is it called "Sale _Workflow_" and not just "Sale"?

"Workflow" gives the idea the enhancements should be related to post-sale invoicing and fulfilment flows.
What about enhancements on Quotations/Sales Orders that focus on the pre-sale process?

**Comment by bwrsandman** [comment]
What is the news on this?
@dreispt Did you find your answer?
