### ISSUE TITLE
Feature request/intent: partner allotment

### ISSUE THREAD

**Issue by clonedagain** [OCA/sale-workflow#206]
As discussed in https://github.com/odoo/odoo/issues/5371, partner allotment can be entered in the standard v8 but it is not actually implemented.

@Solanki-Shamji proposed an initial implementation by @Openies here: https://www.odoo.com/apps/modules/8.0/line_ship/
Improvements and progress can be watched here : https://github.com/OCA/sale-workflow/pull/207

**Comment by clonedagain** [comment]
@Solanki-Shamji would you like to cooperate with me on this topic?

**Comment by clonedagain** [comment]
@jgrandguillaume @eLBati @tafaRU do you agree that these requirements fit the project?

**Comment by clonedagain** [comment]
@openies I'm forking https://github.com/Openies/OdooLineShip to improve it, please reply if you'd like to cooperate.

**Comment by Openies** [comment]
Thanks for improvement suggestion, and yes we like to cooperate in all
case.

On Fri, Sep 4, 2015 at 9:42 PM, Lionel Sausin notifications@github.com
wrote:

> @openies https://github.com/openies I'm forking
> https://github.com/Openies/OdooLineShip to improve it, please reply if
> you'd like to cooperate.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OCA/sale-workflow/issues/206#issuecomment-137779479.

## 

Openies
Ingenious Effective Solutions

**Comment by clonedagain** [comment]
@Openies would you accept to sign the OCA's license agreement? The details are explained at https://odoo-community.org/page/cla
If you don't agree with that we won't be able to merge this in OCA's project but we can still work together aside from OCA.

**Comment by clonedagain** [comment]
In the sale order line tree-view, I initially wanted to reuse the allotment of the previous line of the same order, so users don't have to enter it repeatedly.
Unfortunately I couldn't find a way to do so if someone has an idea please let me know.

**Comment by clonedagain** [comment]
I'm also having quite a hard time porting the code to v8 API, since it overrides v7 methods. So I'm leaving it as @Openies wrote it.
