### ISSUE TITLE
[15.0] sale_invoice_plan : impossible to edit next invoice plan date after the first invoice is created

### ISSUE THREAD

**Issue by tarbib** [OCA/sale-workflow#2064]
Steps to reproduce : 

- Create a SO
- Use invoice plan 
- Create the first invoice by plan

Current behavior : 
The invoice plan next invoice dates are not editable anymore

https://user-images.githubusercontent.com/2255433/172868339-a11714e6-3c17-4274-8856-041c6a3de48d.mp4

Is there any reason for this?
We're thinking of making next invoices plan dates editable even after the first invoice is created.

Ping @kittiu

**Comment by kittiu** [comment]
@tarbib unfortunately, it is just that the sale_invoice_plan is not as mature as purchase_invoice_plan, as we don't use it much. Many improvement was introduced in purchase side as we use it much more cases, including,

1. the one you mentions.
2. freeze the invoiced amount even when the PO line has new amount (recompute only remaining)
3. Auto compute the last installment amount (to finally equal to the PO amount)
etc. I can't remember.

![image](https://user-images.githubusercontent.com/1973598/172908772-1f42a6a5-ffbd-4642-9451-349fe30b1223.png)

You can check https://github.com/OCA/purchase-workflow/pulls?q=is%3Apr+purchase_invoice_plan
