### ISSUE TITLE
Sale Fixed Discount Invoice Tax Miscalculation

### ISSUE THREAD

**Issue by bashierelbashier** [OCA/sale-workflow#2066]
Invoice created from a sales order has a miscalculated tax amount. It is calculated before applying the discount.

Name of the module: 
sale_fixed_discount

Description:
When I create a customer invoice from a sales order that has a fixed discount applied, the tax on the invoice line is computed before applying the discount. For instance, I have a sale order line with 800 price and 400 discount, the subtotal is 400 and the tax is properly computed 60. But when I click on create invoice the invoice is created with the correct price, discount, subtotal but the tax is computed based on the price before applying the discount.

Steps to reproduce:
Create a sales order with only one line. Set the price to 800 USD and the discount to 400 USD. Choose a 15% tax to have 60 USD tax amount. The sales order is totally correct. Confirm it and then create an invoice choosing regular invoice from the wizard. The invoice will be created with a line having 800 USD price, 400 USD discount, 400 USD subtotal but the tax amount is 120 (calculated before applying the discount).

Expected behavior:
When I create an invoice with the above mentioned details the invoice should calculate the tax amount after applying the discount.

Attached is an invoice created from a sales order with the details mentioned above.

![Screenshot from 2022-06-10 13-59-12](https://user-images.githubusercontent.com/37061872/173056171-fe3d132c-18a2-4949-97cb-b5152aa3aa19.png)

**Comment by HunainAhmedKhan** [comment]
is i fixed or still pending? i am also facing this issue in v15
