### ISSUE TITLE
v[14] sale_tier_validation does not work well when customer sign and approve online

### ISSUE THREAD

**Issue by bunhin** [OCA/sale-workflow#2080]
## Module
Sale_tier_validation

## Describe the bug
Because sale order is designed with the possibility for the customer to approve online (send via email, then the customer to sign and approve)
the sale tier_validation is blocking this feature with the message weird enough for the customer
 

1. Install the module
2. Define tier definition 
3. create sales quotation
4. send the quotation by email (click send by email) to the customer
5. Customer accepts and signs to agree and confirm
6. But the tier validation is then triggered at that point, making the signing process seem blocked with the message not proper enough and giving a sense that the signing is not successful but the signature is recorded in the sales record.

**Expected behavior**
Need to have some adjustments for the module to work well with customer online confirmation.

**Comment by rousseldenis** [comment]
Hi @bunhin maybe you need to define the validation rule that allow to exclude orders that have the 'require_signature' field to True.
