### ISSUE TITLE
Bug: sale_order_revision  not compatible with  duplicate

### ISSUE THREAD

**Issue by liuaiqun** [OCA/sale-workflow#210]
test case:
step1:   create a sale order,  save it..   (say PO0001)
step2:   use More | Duplicate,  create new sale order, save it. (say PO0002)
step3,   cancel the new  order (PO0002), and  push the button of " new Copy of Quotation"
it sayes  "Constraint Error: Order Reference and revision must be unique per Company."

the Bug reason:
in PO0002, the filed unrevisioned_name is PO0001, it should be  PO0002

suggested solution:
in the code:
    unrevisioned_name = fields.Char('Order Reference',
                                    copy=True,
                                    readonly=True)
chanded to
    unrevisioned_name = fields.Char('Order Reference',
                                    copy=False,
                                    readonly=True)

**Comment by eLBati** [comment]
Thanks @liuaiqun , does the changes of PR https://github.com/OCA/sale-workflow/pull/186 solve your issue?
