### ISSUE TITLE
[14.0] sale_automatic_workflow: Duplicate invoice for Already refunded invoice

### ISSUE THREAD

**Issue by atchuthan** [OCA/sale-workflow#2109]
The option to create invoice and validate invoice in Sale Automatic workflow works for normal cases.  But, when the invoice created with automatic workflow is paid and refunded (credit note).  Then, the scheduler creates once again an invoice.

## Module
sale_automatic_workflow

## Describe the bug
Duplicate invoice created for already refunded invoice

## To Reproduce
**Affected versions**: 14.0

1. Create a SO and add automatic workflow in which create invoice & validate invoice is selected and confirm the SO.
2. An invoice will be created and validated by scheduled action.
3. Create a refund/credit-note for the invoice created after the invoice is paid.
4. Execute the scheduler once again, a new invoice will be created. 

**Expected behavior**
No invoice is created when the invoice is refunded by user.

cc: @SodexisTeam 

Suggestions on improvements are welcome too
Thanks

**Comment by atchuthan** [comment]
We plan to add an option in Automatic workflow configuration to skip SO's that have refund invoice linked to it.  Is there a better solution?  Please let us know.

**Comment by atchuthan** [comment]
@OCA/oca-contributors suggestions are much appreciated.  Thanks

**Comment by elvise** [comment]
@atchuthan can you post a snap about your domain configuration ?

**Comment by atchuthan** [comment]
> @atchuthan can you post a snap about your domain configuration ?

@elvise What does this issue have to do with the domain configuration?

**Comment by grindtildeath** [comment]
@atchuthan 
We had such an issue for one our customer and we solved it by adding an extra condition in the domain with `('invoice_count', '=', 0)`, so that if an invoice exists it will not generate a new one. I guess this could be integrated in the domain configuration of the create invoice filter.

**Comment by JordiMForgeFlow** [comment]
Hi all,

We had a similar issue caused by Odoo standard deducting the refunded qty of SO Lines from the qty invoiced, putting the line back again as 'to invoice'. We developed this module which may help you: https://github.com/OCA/account-invoicing/tree/14.0/sale_line_refund_to_invoice_qty

**Comment by gaikaz** [comment]
@atchuthan 
Please don't tag the whole **oca-contributors** team on every PR of yours. That's 1k+ people you are pinging at once.
I don't know how others react to this or if there is anything officially written about pinging on Github. I think at most you should tag the maintainers of this repo and still, preferably after some time (let's say a week...) when your PR is not being reviewed.

**Comment by atchuthan** [comment]
> @atchuthan Please don't tag the whole **oca-contributors** team on every PR of yours. That's 1k+ people you are pinging at once. I don't know how others react to this or if there is anything officially written about pinging on Github. I think at most you should tag the maintainers of this repo and still, preferably after some time (let's say a week...) when your PR is not being reviewed.

Okay, I will use maintainers next time.  Thanks for the info.

**Comment by atchuthan** [comment]
> @atchuthan We had such an issue for one our customer and we solved it by adding an extra condition in the domain with `('invoice_count', '=', 0)`, so that if an invoice exists it will not generate a new one. I guess this could be integrated in the domain configuration of the create invoice filter.

@grindtildeath Thanks for the suggestion.  This works for our customer too.
