### ISSUE TITLE
[BUG][8.0] partner_prospect - Partner invoiced is prospect

### ISSUE THREAD

**Issue by rafaelbn** [OCA/sale-workflow#215]
module: partner_prospect
version: 8.0

**Steps to reproduce**
- Create a Partner who is a company
- Create a Contact with Parent the company created in the step before
- Invoice to the contact

**Current behavior**
- The contact and the company are still prospect

![2015-09-22_1-43-15](https://cloud.githubusercontent.com/assets/8736623/10008156/eb7956ae-60cb-11e5-8118-d76148aef1a8.png)

**Expected behavior**
- After invoiced the contact and the company are not prospect, are clients.

**Comment by rafaelbn** [comment]
Refers to https://github.com/OCA/sale-workflow/tree/8.0/partner_prospect

**Comment by rafaelbn** [comment]
Pleas @oihane could you review this issue. Thanks

cc @pedrobaeza

**Comment by oihane** [comment]
Does it continue to do it after this PR, https://github.com/OCA/sale-workflow/pull/217?

I thought I did it. I'm trying to check it on runbot but it is failing

**Comment by pedrobaeza** [comment]
@oihane, can you check this again?

**Comment by Daniel-CA** [comment]
This bug is fixed, can be closed.
