### ISSUE TITLE
[15.0] sale_product_set: Dependency 'onchange_helper'

### ISSUE THREAD

**Issue by furkanguemueser** [OCA/sale-workflow#2171]
## Module
sale_product_set

## Describe the bug
This module has a dependency called 'onchange_helper' which isn't in this project.

**Comment by legalsylvain** [comment]
That's not a bug. 
You should install this OCA module on your instance. 
Regards.

**Comment by furkanguemueser** [comment]
> That's not a bug. You should install this OCA module on your instance. Regards.

Where can i find this module 'onchange_helper'.

Regards.

**Comment by CRogos** [comment]
It's part of the [server-tools](https://github.com/OCA/server-tools/tree/15.0)
