### ISSUE TITLE
[15.0] sale_blanket_order Translatations

### ISSUE THREAD

**Issue by cyrilmanuel** [OCA/sale-workflow#2193]
We need the translation fr on the module sale_blanket_order but we did a mistake. we did them for the language fr_FR.po but we want them to the french language (fr.po).

Is it possible to transfert the translations fr_FR.po into the fr.po language.

Maybe you know how to do this @sbidoul

**Comment by sbidoul** [comment]
If you are sure there are no pending translations in that file in weblate, you could rename it in GitHub. This operations on .po* files in GitHub should be exceptional, but it this case that should be ok.

**Comment by cyrilmanuel** [comment]
Hi, we have pending translations made by us because we have started the translate in fr language just before the creation of this issue... and we don't have the access to delete them. 

what can we do ?

**Comment by cyrilmanuel** [comment]
hello @sbidoul, 

Do you have an idea about this issue ?

**Comment by sbidoul** [comment]
In weblate you can export/import .po files, I think. That's probably the easiest in your case.

**Comment by cyrilmanuel** [comment]
Thanks you, it's done, have a nice day
