### ISSUE TITLE
How to update if Module installed

### ISSUE THREAD

**Issue by l-arnold** [OCA/sale-workflow#220]
When I go to Configuration/Sales/Payment Methods I am returning the traceback that ends with the following.  I realize I could "uninstall" and "reinstall" but doing so wants to strip the whole connector structure out it seems.
Have tried -u -d commands on a Manual openerp-server startup. Does not return errors but I am not getting enough information when I manually start and stop the server this way.

Any Thoughts?  (tracelog below)

  File "/opt/openerp/odoo/openerp/models.py", line 3302, in _read_from_database
    cr.execute(query_str, [tuple(sub_ids)] + where_params)
  File "/opt/openerp/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/opt/openerp/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column sale_workflow_process.section_id does not exist
LINE 1: ..._is_order_date","sale_workflow_process"."warning","sale_work...
                                                             ^

**Comment by l-arnold** [comment]
I did go ahead and "uninstall" plus "reinstall".  Errors gone but also don't have a connection set up right now.  Hope reinstalling won't "duplicate" all my prior imports (could still go back to snapshot point).

**Comment by yvaucher** [comment]
Hello @l-arnold could you tell us for which module it appends ?

**Comment by pedrobaeza** [comment]
No answer, so I close.
