### ISSUE TITLE
[15] sale_order_type

### ISSUE THREAD

**Issue by ghost** [OCA/sale-workflow#2233]
## Module
[15] sale_order_type

## Describe the bug
If a type of sales order is set to an individual type customer and the  quotation  is created from the customer smart button "Sales", it does not take the type of order established to the customer, but the first in the list. It also doesn't happen if the quote is created from a CRM opportunity for that individual customer.
Even if the client is changed on the quotation, the data is not updated.
It is only created correctly if the quotation is made from the sales module selecting the customer on the quotation.
## To Reproduce
**Affected versions**:
Detected on V15. Not tested in previous versions.

1. Create a new sale order type
2. Asssign it to a individual customer.
3. Acces to customer's sales from the smart button of sales of the customer and create a new one. Error case 1
4. Create a quotation from a opportuntty of this individual customer. Error case 2

**Expected behavior**
The default sale order type on the quotations should be the one assigned to a individual customer regardless of where the budget is created from

**Comment by ghost** [comment]
Hello,
Has someone could check this issue?
Thanks

**Comment by chusamo** [comment]
@gelo-landoo Hello I'm not able to reproduce the issue. Since in my 15 CE is working properly
![sale_order_type](https://github.com/OCA/sale-workflow/assets/31690536/a5016f5d-876e-48fa-b226-83de2a0246da)
