### ISSUE TITLE
[portal_sale_personal_data_only] Split for sale and invoice

### ISSUE THREAD

**Issue by rafaelbn** [OCA/sale-workflow#2236]
Hello,

Module [portal_sale_personal_data_only](https://github.com/OCA/sale-workflow/tree/14.0/portal_sale_personal_data_only) includes security rules for sales and invoices and it forces to depend in [sales](https://github.com/OCA/sale-workflow/blob/14.0/portal_sale_personal_data_only/__manifest__.py#L10)

Sales: https://github.com/OCA/sale-workflow/blob/14.0/portal_sale_personal_data_only/security/security.xml#L3

Invoices: https://github.com/OCA/sale-workflow/blob/14.0/portal_sale_personal_data_only/security/security.xml#L19

We have the use case with the same problem (IMHO a Odoo BUG...) but client don't use sales, just invoicing.

I guess it's not a problem and in fact make sense to split it.

Do you agree?

cc @pedrobaeza @chienandalu @victoralmau @kirca  (last PRs I saw)

**Comment by pedrobaeza** [comment]
A split adding `portal_account_personal_data_only` seems OK.

**Comment by yajo** [comment]
MIG+REF in https://github.com/OCA/account-invoicing/pull/1275 and https://github.com/OCA/sale-workflow/pull/2243.
