### ISSUE TITLE
[8.0] Since three days, tests are broken because of ignored oca_dependencies.txt

### ISSUE THREAD

**Issue by StefanRijnhart** [OCA/sale-workflow#228]
Tests of 8.0 are currently broken. 
sale_owner_stock_sourcing in this repo has a dependency on stock_ownership_availability_rules, which can be found at https://github.com/OCA/stock-logistics-workflow/tree/8.0/stock_ownership_availability_rules. The stock-logistics-workflow repository is mentioned properly in https://github.com/OCA/sale-workflow/blob/8.0/oca_dependencies.txt, but like the other repos mentioned in this file they seem not to be present in the build.

```
Creating instance:

/home/travis/odoo-8.0/openerp-server -d openerp_template --log-level=warn --stop-after-init --addons-path /home/travis/build/OCA/sale-workflow,/home/travis/odoo-8.0/addons --init account,sale,account_cutoff_prepaid,stock_ownership_availability_rules,web_context_tunnel,base,sale_stock,sale_layout,stock

2015-10-18 08:55:39,878 22836 WARNING openerp_template openerp.modules.loading: invalid module names, ignored: account_cutoff_prepaid, stock_ownership_availability_rules, web_context_tunnel
```

https://travis-ci.org/OCA/sale-workflow/jobs/86005527

**Comment by gurneyalex** [comment]
I see OCA/maintainer-quality-tools/pull/275 fixing OCA/maintainer-quality-tools/pull/274 which could be related. 

@pedrobaeza do you think we should revert that merge for now?

**Comment by gurneyalex** [comment]
cc @dreispt

**Comment by pedrobaeza** [comment]
OK, I have the problem. I'll make a PR in minutes.

**Comment by StefanRijnhart** [comment]
Thanks both!

**Comment by gurneyalex** [comment]
many thanks... currently attending  pyconfr which is not the ideal place for OCA bugfixing...

**Comment by pedrobaeza** [comment]
Here you have: https://github.com/OCA/maintainer-quality-tools/pull/282
