### ISSUE TITLE
sale_advance_payment: Negative "zero" residual amount

### ISSUE THREAD

**Issue by gaikaz** [OCA/sale-workflow#2480]
Sometimes, the residual amount becomes a "negative zero" when the Sale Order if fully paid.
To be fair, I'm not really sure how to reproduce it, but it's clearly a rounding and/or logic bug with how residual amount is computed.

Module: **sale_advance_payment**
Affected versions: **15.0** (at least)

**Expected behavior**
When the Sale Order get's marked as "PAID", might as well set the residual amount as just zero without actually trying to compute it.

![image](https://user-images.githubusercontent.com/17097810/232308524-4295d13c-a78a-46d0-8c14-dd0af9d3aa4b.png)

**Comment by Mantux11** [comment]
I made a fix here, simple solution, but I think this could prevent `amount_residual` form being with negative zero:

https://github.com/OCA/sale-workflow/pull/2541

**Comment by yaazkal** [comment]
Since this has been merged, I think the issue should be closed.

Regards.

**Comment by gaikaz** [comment]
Thanks @yaazkal 
Sure thing.
