### ISSUE TITLE
[8.0][sale-rental] Onchange of quantity triggers 2 messages in warning pop-up

### ISSUE THREAD

**Issue by atchuthan** [OCA/sale-workflow#255]
We simulated the issue in the OCA runbot.
URL: http://3138577-8-0-1a3142.runbot1.odoo-community.org/web?db=3138577-8-0-1a3142-all
OCA runbot: https://runbot.odoo-community.org/runbot/repo/github-com-oca-sale-workflow-167

[This issue may be due to https://github.com/odoo/odoo/commit/9671ae2a2d116cd1d8f6196b125b92b95ce98f6f]

Product selected at Sales order line
![image](https://cloud.githubusercontent.com/assets/4667326/12047808/c11b9c94-aef7-11e5-9e89-323a729a5024.png)

Warning message shown
![image](https://cloud.githubusercontent.com/assets/4667326/12047798/98c2405e-aef7-11e5-8f21-420ea33e707d.png)

**Comment by atchuthan** [comment]
@ beledouxdenis, please take a quick glance at this issue.

**Comment by pedrobaeza** [comment]
@atchuthan is this fixed?

**Comment by atchuthan** [comment]
We migrated the customer to latest version, so I couldn't test in 8.0.  So, closing the ticket
