### ISSUE TITLE
Sale Order Revision Installation Error

### ISSUE THREAD

**Issue by MayC2023** [OCA/sale-workflow#2600]
## Module
Sale Order Revision

## Describe the bug
Error while import the sale order revision module. The sale management module is not able to access after installation of the sale order module.
![Screenshot 2023-07-12 122410](https://github.com/OCA/sale-workflow/assets/139311884/37ed8879-45b9-4fac-9a13-30da14be20f5)

## To Reproduce
Odoo saas~16.2+e (Enterprise Edition)

1. Apps > Import Module

**Comment by pedrobaeza** [comment]
The module is not for an intermediate SaaS version. In fact, in Odoo online you can't install code modules. The import module option is just for data modules.

Closing as invalid issue.
