### ISSUE TITLE
[8.0][sale_procurement_group_by_line] Recreate pickings doesn't show View Delivery Orders button

### ISSUE THREAD

**Issue by kenvac** [OCA/sale-workflow#264]
Hi Friends,

Just found bug where group_id always created on recreating deliveries from order
## How to reproduce bug:
- Create and confirm the sale order
- Cancel the pickings
- Recreate picking from order
- Once the pickings are recreated the **View Delivery order** is no longer visible. 

Let me know if you guys need any more information on this. 

Regards,
Kinner

**Comment by StefanRijnhart** [comment]
PR merged. Thanks for fixing this!
