### ISSUE TITLE
[RFC] invoice_periodicity especific module

### ISSUE THREAD

**Issue by rafaelbn** [OCA/sale-workflow#2669]
### RFQ: Invoice Management Enhancement in Odoo

**Project Summary:**
We are looking to enhance our current Odoo ERP system's capabilities regarding the management of invoice data for our customers. The key areas of focus include the payment term, payment method, and invoice periodicity.

**Functional Requirements:**

1. **Payment Term:** 
    - Define the due date of the invoice.
    - Options include but are not limited to: net 15, net 30, net 60, etc.
    - Should be attached to the customer profile in the system.

- [x] **This is covered by account payment terms in CORE + the OCA Extension**

2. **Payment Method:** 
    - Define how the customer prefers to settle the invoice.
    - Options include but are not limited to: bank transfer, credit card, check.
    - Should be attached to the customer profile in the system.

- [x] **This is covered by account payment method in core (Odoo R&D team improving for Odoo17) or account payment mode in OCA** 

3. **Invoice Periodicity:**
    - Define how often the customer wishes to be billed.
    - Options include but are not limited to: monthly, quarterly, annually.
    - Should be attached to the customer profile in the system.

- [x] **We are goind to develop this module**

### Analysed actually in OCA and discarded:

- https://github.com/OCA/sale-workflow/tree/16.0/sale_order_type
- Big and complicated pack of modules with lot of dependencies
    - https://github.com/OCA/account-invoicing/tree/16.0/partner_invoicing_mode
        - https://github.com/OCA/account-invoicing/tree/16.0/partner_invoicing_mode_at_shipping
        - https://github.com/OCA/account-invoicing/tree/16.0/partner_invoicing_mode_monthly
        - https://github.com/OCA/account-invoicing/pull/1534
        - https://github.com/OCA/account-invoicing/pull/1532

### Prototype Requirements:

1. **UI Integration:** 
    - The above fields need to be seamlessly integrated into the current Odoo customer profile page.
    - The UI should be intuitive and easy for our staff to understand and fill out.

2. **Database Enhancement:** 
    - The underlying database should be modified to hold this new data without affecting current operations.
    - Data integrity and reliability should be ensured.

3. **Testing:** 
    - The prototype should be fully functional for testing purposes.
    - We need to test with real-world scenarios to ensure its robustness.

**Timeline:** 
We're looking to have a prototype ready within 3 days and the final version deployed within 1 week [specific timeframe, e.g., 8 weeks].

### DRAFT PROTOTYPE

_Note: without technical knowledge just GPT-4_

**Data Model**

```
from odoo import models, fields

class PartnerInvoiceInfo(models.Model):
    _inherit = 'res.partner'

    invoice_periodicity = fields.Selection([
            ('monthly', 'Mensual'),
            ('quarterly', 'Trimestral'),
            ('yearly', 'Anual')
        ], string='Periodicidad de Facturación')
```

**Views**

```
<?xml version="1.0" encoding="UTF-8"?>
<odoo>
    <record id="view_partner_form" model="ir.ui.view">
        <field name="name">res.partner.form.inherit</field>
        <field name="model">res.partner</field>
        <field name="inherit_id" ref="base.view_partner_form"/>
        <field name="arch" type="xml">
            <xpath expr="//field[@name='vat']" position="after"> (this is Wrong, Tab Sales)
                <field name="invoice_periodicity"/>
            </xpath>
        </field>
    </record>
</odoo>
```

@moduon MT-3519 @Shide

**Comment by Shide** [comment]
@rafaelbn Task 3: https://github.com/OCA/sale-workflow/pull/2680, https://github.com/OCA/sale-workflow/pull/2681

**Comment by rafaelbn** [comment]
Thank you @Shide 

Closing https://github.com/OCA/sale-workflow/tree/16.0/sale_invoice_frequency
