### ISSUE TITLE
Revisions for sale orders Question..need fix

### ISSUE THREAD

**Issue by jaronemo** [OCA/sale-workflow#267]
Dears
1. origin sale order (qty = 50)
   ![image](https://cloud.githubusercontent.com/assets/8476734/13346107/ef1ebb4c-dc9e-11e5-89cc-175f495e5792.png)
2. Delivery Order (qty=50)
   ![image](https://cloud.githubusercontent.com/assets/8476734/13346165/4587dc20-dc9f-11e5-9967-0fda30aa458a.png)

3.cacel sale order and create reversion fix qty to 30
![image](https://cloud.githubusercontent.com/assets/8476734/13346180/6e8c70a4-dc9f-11e5-94ea-4b458cec7cee.png)

4.Delivery Order tree 
![image](https://cloud.githubusercontent.com/assets/8476734/13346191/845cb4a2-dc9f-11e5-9cc8-c344ae80222b.png)

5.Delivery Order Form (qty not 30...is origin qty = 50)

![image](https://cloud.githubusercontent.com/assets/8476734/13346201/9c096370-dc9f-11e5-9ebb-6131d1cbbd5c.png)

**Comment by pedrobaeza** [comment]
Please propose then the same fix

**Comment by jaronemo** [comment]
Dears:

This module issue..problem..is no need fix?

**Comment by eLBati** [comment]
Hello @jaronemo , PR https://github.com/OCA/sale-workflow/pull/306 should fix this

**Comment by pedrobaeza** [comment]
Fixed, so I close.
