### ISSUE TITLE
Sale Order Reversion problem

### ISSUE THREAD

**Issue by jaronemo** [OCA/sale-workflow#268]
Dears

This Module like 
https://github.com/OCA/purchase-workflow/issues/202 

same problem..

**Comment by pedrobaeza** [comment]
Duplicated

**Comment by eLBati** [comment]
It seems https://github.com/OCA/sale-workflow/issues/267 and https://github.com/OCA/purchase-workflow/issues/202 are different problems. @jaronemo am i right?

**Comment by jaronemo** [comment]
YES

**Comment by jaronemo** [comment]
mean is duplicated problem on sale order reversion..same....
