### ISSUE TITLE
[8.0][sale_order_lot_selection]Not working for multiline sale orders

### ISSUE THREAD

**Issue by AntMoreno** [OCA/sale-workflow#269]
Hi to all

Tested on RunBot the addon worked fine, but tested on a brand new local instance (8.0.20160314) with a new DB (only with modules Sale, Purchase and WH) it doesn't work for sale orders with multiple lines.

**Steps to reproduce:**

1.- Create a new Sale Order with 2 or more lines of products
2.- Assign lot to every line (ensure lot has stock available)
3.- Confirm the Sale Order
4.- Go to the Delivery Order

**Result:**

Only the first line in the Delivery Order is in state "Available" and reserved, the rest of the lines are in state "Waiting Availability" and not reserved

**Expected:**

All the lines in the Delivery Order should be in state "Available" and with availability set to the quantity reserved.

**Additional information:**

If, after step 4, we click on "Transfer" to open the Transfer Details Wizard, only the first line shows up. If instead of clicking on "Transfer" we click on "Recheck Availability" first, then in "Transfer", all products, quantitys and lots show up in the "Transfer Details Wizard" form. So it seems lots are not assigned to procurement for lines 2nd and up.

Thank you and best regards

**Comment by antoniocanovas** [comment]
The same problem, only the first product appears as "reserved".

**Comment by antoniocanovas** [comment]
... but when I check avalilability the lots selected in the sale order is assigned ok in all the lines.

**Comment by AntMoreno** [comment]
In my case a "Recheck availability", "Transfer" and "Force availability" buttons are shown altogether, instead of the "Check availability" and "Force availability" buttons. If I click on "Recheck availability" selected lots are assigned, but if I click on "Transfer" only the product and lot for the first line is included in the "Transfer wizard".

As I understand it, the right behaviour should be that once you select lots in the Sale Order and confirm it, in the Delivery Order all lines should appear as reserved, so when you click on "Transfer", lots selected in the Sale Order should appear in the "Transfer wizard" for all lines, not only for the first one, without the necessity of clicking either "Check availability" or "Recheck availability" again.

**Comment by eLBati** [comment]
Hello @AntMoreno @antoniocanovas 
PR https://github.com/OCA/sale-workflow/pull/307 should fix the problem

**Comment by AntMoreno** [comment]
Tested and confirm PR 307 fixed the issue. Thank you.
