### ISSUE TITLE
sale_quotation_number: problem when quotation sequence is edited

### ISSUE THREAD

**Issue by manuelregidor** [OCA/sale-workflow#2709]
With the current module, the sale order number is only changed from the quotation sequence to the sale order sequence if the first two first characters of the sale order number in draft state are "SQ", which is the default prefix. If this sequence is edited, the sale order number in quotation state will be kept when the sale order is validated and it will not use the sequence for validated sale orders.

A possible solution would be to add a boolean field to sale orders to indicate whether the quotation sequence has been used. This field will be set to True when a new sale order is created and will return to False when the sale order is validated. When the sale order is validated, it will be checked whether the used sequence is the quotation sequence using this new field. If so, the sale order number will be changed. With this solution, the change of the number will be applied no matter what is the sequence configuration. It would also be interesting to add a field to res.company to set the sale quotation sequence that has to be used.

**Comment by HaraldPanten** [comment]
@pedrobaeza @etobella  Do you mind having a look at this? Or... do you prefer us to directly create a new PR with a possible solution?

THX

**Comment by pedrobaeza** [comment]
We are not using this module, so I can't say.
