### ISSUE TITLE
[16] sale_order_product_recommendation: dont load recommended products

### ISSUE THREAD

**Issue by fcvalgar** [OCA/sale-workflow#2739]
## Module
sale_order_product_recommendation

## Describe the bug
The module dont load the recommended products with any of the configurations. 
I have used pricelist and last sales.

## To Reproduce
V16

I have followed the instructions in the module and created a sales order for several companies that have confirmed and invoiced sales. 

Can you help me @sergio-teruel ? Is it a Runboat problem? 

Thank you.

MT-3035

**Comment by fcvalgar** [comment]
MT-3010

**Comment by sergio-teruel** [comment]
Sorry @fcvalgar I tested the sale order product recommendation module and everything seems like...

**Comment by fcvalgar** [comment]
Sorry @sergio-teruel It was my mistake in the testing of the module. I am sorry for any inconvenience this may have caused you. I will increase my testing.

Close.
