### ISSUE TITLE
[16] sale_order_line_price_history - The "Set Price" button does not update the price of the line.

### ISSUE THREAD

**Issue by Gelojr** [OCA/sale-workflow#2744]
## Module
sale_order_line_price_history
## Describe the bug
The "Set Price" button does not update the price of the line.
## To Reproduce
**Affected versions**:
16
13,14 #1723 
https://www.loom.com/share/d667e5e40d8b4ddca11bd0145ba1cdba?sid=a6cc3d48-03a3-4b85-a873-0d40b73a72f3

**Expected behavior**
The price of the line should be $295 after setting the price.
**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

@moduon MT-3593

**Comment by sergio-teruel** [comment]
Hi @Gelojr we check the migration, and it have the same behavior that older versions.

**Comment by pedrobaeza** [comment]
In fact, it's highlighted on the roadmap/known issues: https://github.com/OCA/sale-workflow/blob/16.0/sale_order_line_price_history/readme/ROADMAP.rst

**Comment by Gelojr** [comment]
@sergio-teruel But the readme says: 

> This module extends the Sales functionality to allow you to view the price history of a product from a sales order line and **set one of those old prices on the sales order line**.

In that case, the part in bold is not correct, because this functionality does not work and should be removed.

@pedrobaeza In the roadmap it says 

> It is not possible to set a price from the tree view of the wizard lines, currently **it can only be done from the form view of those lines (by clicking on one of them)**. **This is not solved by simply putting a 'Set price' button in the wizard lines** because that button will be disabled since when the wizard is launched there is still no wizard record in the database (this is an Odoo limitation).

From what the roadmap says, what it means is that it is not possible to change the price directly from the lines of the wizard.
![image](https://github.com/OCA/sale-workflow/assets/147538094/03bd25bd-4595-4856-8b39-77ada4370e96)
But it is from the form view of those lines 
![image](https://github.com/OCA/sale-workflow/assets/147538094/acde321d-a4ca-4cce-a002-326e0ee85e5f)
If this is not the case, and it is not possible to change the price and use an old price, I think that part of the readme should be removed, as I told @sergio-teruel

**Comment by pedrobaeza** [comment]
As a note, the price is set, but you have to reload the window to see it. Anyway, if the README is not correct, please propose the PR amending it/making the precision.
