### ISSUE TITLE
sale_force_invoiced install error

### ISSUE THREAD

**Issue by rcoffeehun** [OCA/sale-workflow#2768]
## Module
sale_force_invoiced 

## Describe the bug
I have a problem with the sale_force_invoiced module. I installed the sale_force_invoiced-16.0.1.0.0 
Unfortunately during installation I got an error message:

Error while importing module 'sale_force_invoiced'. while parsing /tmp/tmpydkfb1t9/sale_force_invoiced/view/sale_order.xml:3 Error while validating view near: <form string="Sales Order" class="o_sale_order"> <header> <field name="authorized_transaction_ids" invisible="1"/> <button name="payment_action_capture" type="object" data-hotkey="shift+g" string="Capture Transaction" class="oe_highlight" attrs="{'invisible': [('authorized_transaction_ids', '=', [])]}"/> <button name="payment_action_void" type="object" string="Void Transaction" data-hotkey="shift+v" confirm="Are you sure you want to void the authorized transaction? This action can't be undone." attrs="{'invisible': [('authorized_transaction_ids', '=', [])]}"/> Field "force_invoiced" does not exist in model "sale.order" View error context: {'file': '/tmp/tmpydkfb1t9/sale_force_invoiced/view/sale_order.xml', 'line': 3, 'name': 'sale.order.form', 'view': ir.ui.view(3699,), 'view.model': 'sale.order', 'view.parent': ir.ui.view(1698,), 'xmlid': 'view_order_form'} Make sure those modules are installed and try again.

**Comment by pedrobaeza** [comment]
It seems you are trying to "import the module", but that's not possible for code modules (only for data ones). Anyway, the module is working, as you can see on runboat, so closing.

**Comment by rcoffeehun** [comment]
> It seems you are trying to "import the module", but that's not possible for code modules (only for data ones). Anyway, the module is working, as you can see on runboat, so closing.

Is it possible to improve? My sales system has crashed
Gabor

**Comment by pedrobaeza** [comment]
It's not a problem of the module, but what you are doing in your system. There's a saying here: "If you don't know what to do, don't touch". Contact an specialist to return your system to an stable situation.
