### ISSUE TITLE
[16.0] sale_order_product_picker: cannot use to edit qtys, after saving for the 1st time

### ISSUE THREAD

**Issue by yajo** [OCA/sale-workflow#2794]
## Module
sale_order_product_picker

## Describe the bug
After you use the product picker once and save the record, you cannot use it any more. What is worse, you don't get any errors or visual feedback. The changes are just ignored. See:

https://github.com/OCA/sale-workflow/assets/973709/6d2381d9-086b-4216-a5ad-c10cd783f660

## To Reproduce
**Affected versions**: 16.0

Steps to reproduce the behavior: See video above.

**Expected behavior**
Changes should get saved, just like when editing for the 1st time.

**Additional context**
New module from https://github.com/OCA/sale-workflow/pull/2762.

@moduon MT-3930
Ping @CarlosRoca13 @pedrobaeza

**Comment by rafaelbn** [comment]
Hello @CarlosRoca13 ,

Please could you take a look in this issue?

Testing more deeply we found this issue.

cc @Tecnativa TT45382

ping @sergio-teruel @carlosdauden

Thank you! 😄

**Comment by yajo** [comment]
Fixed in #2796
