### ISSUE TITLE
[16] sale_order_line_price_history - Column size excessive

### ISSUE THREAD

**Issue by Gelojr** [OCA/sale-workflow#2889]
**Is your feature request related to a problem?**
The field size is too large and it is not possible to resize it
![image](https://github.com/OCA/sale-workflow/assets/147538094/fb3eb234-5f54-4bc3-acdf-e9beab812308)

**Describe the solution you'd like**
Do the same as Odoo does for purchases. This way everything is also unified with the same style.
![image](https://github.com/OCA/sale-workflow/assets/147538094/2efe1a3a-fac2-4ef0-8726-45333f6f0172)

@Shide can you check it?
@moduon
MT-3593

**Comment by Shide** [comment]
This is the [PR 2805](https://github.com/OCA/sale-workflow/pull/2805), but some changes are in v15 and need to be ported to v16 before this improvement: https://github.com/OCA/sale-workflow/pull/2800

**Comment by Shide** [comment]
You can review changes in this PR: https://github.com/OCA/sale-workflow/pull/2905

**Comment by rafaelbn** [comment]
@Gelojr solved in https://github.com/OCA/sale-workflow/pull/2905
