### ISSUE TITLE
sale_invoice_policy can't be installed on Odoo.sh from App Store

### ISSUE THREAD

**Issue by kubangab** [OCA/sale-workflow#2964]
## Module
sale_invoice_policy 

## Describe the bug
When installing the module from Odoo App Store to ooo.sh it fails after a while (red dot) and not possible to use in installation.

## To Reproduce
**Affected versions**: 16

1. Open apps.odoo.com
2. Find sale_invoice_policy
3. Press Replay on Odoo.sh
.

**Expected behavior**
After. Odoo.sh has run its tests it should show as a green dot and functioning perfectly.

**Additional context**
Work on prep installation but problem on Odoo.sh

**Comment by pedrobaeza** [comment]
The module is not installable for now. You can see that is installable=False in the manifest. The reasons are explained in other issues and pull requests.
