### ISSUE TITLE
[8.0] [sale_start_end_dates] No demo = no order line view

### ISSUE THREAD

**Issue by JulieSFL** [OCA/sale-workflow#312]
**Using a database with demo data**
When creating a sale order, "Add an item" link opens a window for entering the order line info.

![demo](https://cloud.githubusercontent.com/assets/18582938/16051644/960a0b7a-322e-11e6-98ad-7f2fb9fba53a.png)

**Using a database initialized with option --without-demo=WITHOUT_DEMO**
The window doesn't open. What am I missing?
![nodemo](https://cloud.githubusercontent.com/assets/18582938/16051646/9733d634-322e-11e6-9b28-64c0123cdbaf.png)

I tried it several times with several databases.

**Comment by kryskool** [comment]
Hi, 
The display on sale order line depends on your user groups, add one of these group to change the behavior 
- Manage Product Packaging
-  Manage Secondary Unit of Measure 
-  Properties on lines 

Regards,

**Comment by JulieSFL** [comment]
Thank you for your answer!
