### ISSUE TITLE
[17.0] sale_invoice_policy switch from delivered to ordered qty not working

### ISSUE THREAD

**Issue by Highcooley** [OCA/sale-workflow#3245]
## Module
sale_invoice_policy

## Describe the bug
If the general invoicing and the product's invoicing policy are "on delivered qty" and an SO is changed to "on ordered" qty, the invoice cannot be created (error message, that there is no delivered qty to invoice). 

## To Reproduce
17.0

1. Set the default invoicing policy to "on delivered"
2. Create a product with "on delivered" invoicing policy
3. Create an SO and add the product
4. Change the invoicing policy to "on ordered"
5. Confirm the SO
6. Click on "Create Invoice" and select regular invoice"

**Expected behavior**
If the SOs invoice policy is changed, it should act as if the invoicing policy of the products would be set like this. In the case of switching from "on delivered" to "on ordered", an invoice should be created with the full qty of all products of the SO to be invoiced.

**Comment by Highcooley** [comment]
ping @nguyenminhchien

**Comment by nguyenminhchien** [comment]
Hi @Highcooley , i can't reproduce your case. Check the screencast below, i followed your suggested steps, then the SO was fully invoiced

[Screencast from 25-07-2024 11:58:07.webm](https://github.com/user-attachments/assets/44aaeb57-8e00-4c31-9156-604cfc194344)

**Comment by Highcooley** [comment]
[Solved]
Sale Invoice Policy required needs to be activated:
![2024-08-13_09-47](https://github.com/user-attachments/assets/4eb7c35c-0c9c-4d0c-8d7d-6b72c51591bd)
