### ISSUE TITLE
[9.0] Sale exception

### ISSUE THREAD

**Issue by florian-dacosta** [OCA/sale-workflow#335]
Hello @atchuthan I have an issue with sale_exception module.
When I try to cancel a sale order which was validated using the ignore exception field, it raises exceptions.

I see this part in code and I guess this is the problem : 

```
    @api.multi
    def action_cancel(self):
        for order in self:
            if order.ignore_exception:
                order.ignore_exception = False
        return super(SaleOrder, self).action_cancel()
```

I wonder why we put ignore exception to False in case of cancel?
So if I ignored exception on validation, I won't ever be able to cancel the sale order?

**Comment by atchuthan** [comment]
@florian-dacosta sorry for the late reply

It seems the method I used was to enable the ignore_exception=False for drafted SO after it was cancelled, but I used the wrong method to do the functionality.

I will make a PR such that the value is updated with action_draft()

**Comment by pedrobaeza** [comment]
Closing as there's a PR for this.
