### ISSUE TITLE
Sale Automatic Workflow not Working

### ISSUE THREAD

**Issue by augustosamame** [OCA/sale-workflow#362]
I need to automate Odoo's sales process for a 1 person sales team.
This OCA sale automatic workflow module seems ideal. I am testing it with the automatic runbot here:

http://3273178-9-0-f5b4fb.runbot1.odoo-community.org/web?debug=1

I have setup up a new automatic workflow and checked all the checkboxes:

Validate Order
Confirm and Transfer Picking
Create Invoice
Validate Invoice
Register Payment
Sale Done

so that a confirmed sales order will automatically validate it, get the products out of the warehouse, create the invoice, validate it, mark it as paid and mark the sale done.

However, when I create a new sales order and choose the automatic workflow option, once I save it or confirm it, it does nothing.

Am I missing a step?

**Comment by gurneyalex** [comment]
what version are you using ?

**Comment by augustosamame** [comment]
Thanks for the follow up.
It turns out the module IS working, bit I misunderstood the way it works. It turns out the automations are handled by a cron, which runs at most every 1 minute. So you have to wait up to a minute for the automations to be fired.
It's a little strange to do it this way, instead of having the automation fire at sale confirmation, at least for my use case.

**Comment by bodedra** [comment]
We can close these issue as cron job will take some time at next interval time to execute logic.

@augustosamame Feel free to submit PR to execute logic at sale confirmation.
