### ISSUE TITLE
Erroneous Branch

### ISSUE THREAD

**Issue by lasley** [OCA/sale-workflow#363]
Hi @legalsylvain - Looks like we have a [branch of your's on the OCA side of things](https://github.com/OCA/sale-workflow/tree/legalsylvain-comment-sale_visible_tax). I don't want to delete your branch and make you lose work, so will you please verify you have it locally and delete it on OCA?

_Edit_ Oh I'm not a PSC here, guess I couldn't delete it if I tried!

**Comment by pedrobaeza** [comment]
I'm removing it then.
