### ISSUE TITLE
[RFC] sale_subscription

### ISSUE THREAD

**Issue by lasley** [OCA/sale-workflow#364]
We have a pretty solid `subscription` module in Odoo, but it is not that wieldy from a user perspective. 

This module will add a Create Subscription Wizard in the More menu of a `sale.order`. This wizard will ask the following, then create a `subscription.document.sale` and a `subscription.subscription` for it after asking:

* Interval
* Interval Unit
* First Date (onchange to be Interval + Order Date for ease)
* Notification template (will send this via email if defined)
* Add Followers - followers to add to sale automatically
* Sale Status - Status of sale
* Create Invoice - Whether an invoice should be generated

When a `subscription.document.sale` is created by the `subscription.subscription`, it will automatically create a sale based on the settings of the base document & perform the workflow actions for status, notifications, add followers, etc.

The `sale.order` will gain a `Subscriptions` tab, with the following:
* Base Document - The base `subscription.document.sale` document that is used for configuration
  * Pass-thru some attributes to allow configuration from within the `Subscriptions` tab, instead of requiring nav to document
* Source Document - The `subscription.document.sale` document that was used to create this sale (if any)
* History - Listing of sales created in this subscription (`subscription.subscription.doc_lines.mapped('sale_order_id')`)

Anyone know of anything overlapping with these requirements, ideas of things I'm overlooking, or ways to simplify the plans?

**Comment by pedrobaeza** [comment]
Why not to complete what is already done in OCA/contract?

**Comment by lasley** [comment]
Hmmm I don't think I knew about that repo. I may be able to work with this, thanks @pedrobaeza.

I'll leave this open until I find out for sure though & will provide update.

**Comment by lasley** [comment]
Yup ok we're good here. I'll probably need to add some sort of website component in order to make it fall inline with the new website-based portals, but that's no big deal really.

**Comment by rafaelbn** [comment]
Hi @lasley , I'm quite interested in you developments on this matter. Please let me know. We were thinking about this for a customer because he need contracts for recurring but he sell online membership. It was like ecommerce -> buy online a membership -> this must generate a recurring contract to be renewed monthly and the you will receive some products (food) every month. The main problem was the payment, recurring payments... Odoo with contracts generate recurring invoices buy also must get the payment from paypal, stripe or similar...
Thanks!

**Comment by lasley** [comment]
@rafaelbn - Yeah I need sales too. The whole skipping direct to invoice thing is not really the way that Odoo works anymore.

My plan is to add a simple option to create sales before the invoices, which would hopefully allow for us to share most of the logic existing for Contracts without having to skip directly to invoice.

Does this somewhat fit your requirements too?

**Comment by rafaelbn** [comment]
It doesn't 😉  but as I've understood you need recurring sales order and not invoices. I need invoices directly.
What I don't make an idea is why you want recurring sales order 🤔

**Comment by lasley** [comment]
TBH I don't really care, but Odoo SA has basically forced this workflow with the new website processes. There is no Pay Now on the Invoices in website (unless I'm missing something), the process is instead setup to pay directly on sale orders, and I really don't want to have to design the payment processes over 😦. Maybe I'm just doing it all wrong?

Regarding your requirements, what is missing in the current workflow if not for the sale thing?

**Comment by lasley** [comment]
Oh another advantage to Sale Order vs Invoice is the ability for the custom Website templates via the Online Quote feature. I plan on using this to bill a bunch of different SaaS features, which all could have different terms of use. Using the sale would allow this to be configured on a per-contract basis, which would reiterate the terms (or whatever else I want) during the payment process.

Although maybe a `website_contract` module could correct this, and just provide a viewable terms page on the contract. And a billing workflow. Oh and cancellation.. can't have contracts without cancellation.

**Comment by rafaelbn** [comment]
OK, thanks. One year ago @pedrobaeza and me define different modules to cover this need but we never did it, so your fresh and power are very welcome!

**Comment by lasley** [comment]
@rafaelbn / @pedrobaeza - do you maybe have some links to those prior specs or convos? May help with inspiration

**Comment by pedrobaeza** [comment]
I don't have any, and I think Rafa neither. It was an R&D session without any documentation left.

**Comment by rafaelbn** [comment]
@pedrobaeza we had something defined like payment_recurring, paypal_recurring, ... with some task and descriptions. But I don't have access to that tasks anymore. It was for EyM & MPW.

**Comment by pedrobaeza** [comment]
Yeah, but no way to recover it I'm afraid.

**Comment by lasley** [comment]
😢
