### ISSUE TITLE
Sale rental module don't work on Odoo 9.0

### ISSUE THREAD

**Issue by rgeromegnace** [OCA/sale-workflow#367]
Bonjour,

I installed sale rental module on Odoo 9.0 and I encountered several malfunctions.
I try to follow the old youtube demo video and I was not able to validate properly a rental sale.
When I valid my sale order, Odoo did not propose me to make a delivery so there are no stock move as expected.

Regards,

**Comment by pedrobaeza** [comment]
@alexis-via can you help?

**Comment by pedrobaeza** [comment]
Closing this for triaging it.
