### ISSUE TITLE
sale_sourced_by_line picks incorrect partner_to_invoice

### ISSUE THREAD

**Issue by jonerikceberio** [OCA/sale-workflow#397]
Version 8.0
When sale_sourced_by_line inherits _get_partner_to_invoice (model/stock.py), it searches the sale order lines related to the procurement group of the picking. It is correct, but it does not check if there is a procurement group (the user can create the picking manually). In that case, it searches for all the lines without a procurement group.

**Comment by pedrobaeza** [comment]
Can you please make the PR amending this?
