### ISSUE TITLE
sale_properties_easy_creation

### ISSUE THREAD

**Issue by Mitconsulting** [OCA/sale-workflow#398]
Salve,
ho installato il modulo " sale_properties_easy_creation" sulla versione 8 di odoo ma mi sono accorto di un bug.
Premessa: ho un listino di vendita con in prezzo di vendita che cambia in base alle quantità.
Dopo aver installato il modulo e settato nella configurazione il parametro " Properties on lines",nell'inserimento delle righe all'interno di un ordine di vendita non viene più calcolato il prezzo secondo il listino di vendita.

Ho usato questo modulo perchè ho la necessità solo per alcuni prodotti di applicare una formula per calcolo del prezzo di vendita ma per il restante degli articoli ho bisogno che il prezzo venga calcolato in base al listino.

Qualcuno ha usato questo modulo ed ha notato questa errore?

**Comment by pedrobaeza** [comment]
I close as this is an international forum and messages should be posted in English.
