### ISSUE TITLE
Split module sale_exception in 2 modules

### ISSUE THREAD

**Issue by mourad-ehm** [OCA/sale-workflow#408]
## **Context :**

Module sale_exception is very useful to make configurable the blocking rules on sale order.
This feature is also useful on other objects. We can for example block shipping (or invoice, ...) if some condition are fulfilled.

**Solution proposed :**
We propose to split the module sale_exception on two modules.
1) base_exception :  
    this module contains the basic objects and methods used to manage exceptions.

2) sale_exception : 
 This module inherits from base_exception and add extension to manage exceptions on sales.

### Design:
    
1) base_exception :  (in server-tools ?) 
    - rename object "sale.exception" to "exception.rule"  
    - the field model : selection values returned by a method _get_available_model
   -  add field sub_model : a list off model that must be validate at the same time of model (ex : sale.order.line must be validated a the same time of sale.order validation)
   -  delete field  sale_order_ids
   
   add abstract object "base.exception"
    main_exception_id = fields.Many2one( 'exception.rule',  compute='_get_main_exception',  string='Main Exception',  store=True)
    exception_ids = fields.Many2many('exception.rule', string='Exceptions')
    ignore_exception = fields.Boolean('Ignore Exceptions',  copy=False)

rewrite methods (transform to generic methods).

2) sale_exception : 

- sale_order : inherits from  "base.exception"
 keep the specific sale_order method
- add a menu "Sale exception rules" under Sale/configuration with a filter on models "sale.order" and "sale.order.line"

The views of the contributors to this module are welcome:
@pedrobaeza 
@TheCloneMaster
@atchuthan 
@sbidoul 
@sebastienbeau 
@yvaucher

**Comment by bealdav** [comment]
Thanks @mourad-ehm 

- after porting we could improve sale_exception by add state field to determine from which sale.order state we could evaluate exceptions: to make it more generic (since v9 a confirmed sale can be modified and rules must be evaluate again, and may be to different step).
- if we plan to do the item above, we could rename `base.exception` to `base.rule`, more generic way to deal with different use cases ?: a step here to a subset of a basic workflow feature without bloated workflow engine, I haven't said it but ...

**Comment by jgrandguillaume** [comment]
Hi,

I like this idea !

:+1: for going in this direction.

**Comment by bguillot** [comment]
Seems a good idea to me as well :+1:

**Comment by yvaucher** [comment]
:+1: definitely the way to go if you need to reuse the exception base somewhere else

`base_exception` or `base_rule` module should probably go in `server-tools` repository as `date_range`

**Comment by rvalyi** [comment]
cc @renatonlima I think you will be happy to use that for your invoice_exception module with the Brazilian version too.

**Comment by pedrobaeza** [comment]
Closed to track the rest of the discussion in #775
