### ISSUE TITLE
Todo : Move purchase_order_reorder_lines to purchase-workflow

### ISSUE THREAD

**Issue by max3903** [OCA/sale-workflow#42]
This is just to move 
https://github.com/OCA/sale-workflow/tree/7.0/purchase_order_reorder_lines
to
https://github.com/OCA/purchase-workflow/tree/7.0

**Comment by gurneyalex** [comment]
:+1:

**Comment by zaoral** [comment]
Hello @max3903 

We are working in a purchase_order_reorder_lines similar module with some improves that the current module does not have. This new module is a v8 module.

In discussions with @nhomar we agreed that after finish the module we will make this move of repository of the current purchase_order_reorder_lines and we will propose the new module with the improvements.

Best Regards
