### ISSUE TITLE
[9.0] Runbot warning due to 'must_have_dates', 'type', 'uom_id' constrain

### ISSUE THREAD

**Issue by LoisRForgeFlow** [OCA/sale-workflow#420]
In this pull request https://github.com/OCA/sale-workflow/pull/353 this fields <code>'must_have_dates', 'type', 'uom_id'</code> are added in <a href="https://github.com/akretion/sale-workflow/blob/e544824e533ef3cc67c31f7695758666a36d5f9d/sale_rental/models/product.py#L23">a constrain</a> but they are readonly in their creation (see <a href="https://github.com/OCA/sale-workflow/blob/10.0/sale_start_end_dates/sale.py#L83">one of them</a>).

This is producing a warning in some runbot logs like <a href="https://runbot2.odoo-community.org/runbot/static/build/3280961-418-56844f/logs/job_20_test_all.txt">this one</a> for example and turning the test  :red_circle:.

**Comment by pedrobaeza** [comment]
Can you please make a PR removing then from the constraint decorator?

**Comment by pedrobaeza** [comment]
The PR is done, so I close.
