### ISSUE TITLE
[10.0] sale_product_set: should it be split in 2 modules? product_set and sale_product_set

### ISSUE THREAD

**Issue by jcdrubay** [OCA/sale-workflow#428]
@leemannd 

For a future project, I would probably need to use the concept of `product_set`, but I need a different implementation on the sale order.

I think we could split the module into 2 modules:
 - product_set
 - sale_product_set

Could it be added in the Roadmap?

**Comment by pedrobaeza** [comment]
Yes, it's a good idea. Please make a PR with this roadmap.

**Comment by leemannd** [comment]
@jcdrubay If it makes sense for you to have a different implementation, you're welcome. Just a question, what are you trying to achieve?

**Comment by jcdrubay** [comment]
@leemannd I wish to add a product (set) as the product in my sale order line. Then upon confirmation of the sale order, I will create child objects which will then use the "set lines".

I guess it is similar to using the bom with type phantom but without having to depend on MRP and all its dependencies.

**Comment by pedrobaeza** [comment]
@jcdrubay, for that, you have to see https://github.com/OCA/product-attribute/pull/180, but it's still WIP (we have abandoned for now the project), but the idea is to have full support of procurements and so on.

**Comment by jcdrubay** [comment]
In my case it is a bundle of service products which much more simple than this OCA/product-attribute#180 because there is no stock involved, but later with a different complexity because I will plug it to the project management.

For instance I put the product "ERP Project" in my sale order, upon sale order confirmation I will generate several project tasks:
 - Analysis
 - Implementation
 - Tests
 - Training

But in my Sale Order, I could also sell only an Analysis which upon sale order confirmation will generate a task only for analysis.

**Comment by pedrobaeza** [comment]
For that task see sale_service_project module. It's exactly that need.
