### ISSUE TITLE
Add Set when not in edit mode

### ISSUE THREAD

**Issue by technicomp** [OCA/sale-workflow#430]
It is possible to Add a set while Quotation / SO is not in edit mode. It is also saved automatically since there is no "Save" Button. I think changes to a SO should only be possible when in Edit mode.

**Comment by pedrobaeza** [comment]
That's not the way standard Odoo framework works, so the answer is no.

**Comment by technicomp** [comment]
This was not a question, this was a bug report - right now it is possible to add a set even when the SO is not in edit mode - this should not be possible!

**Comment by pedrobaeza** [comment]
That's exactly the intended behavior as stated.

**Comment by technicomp** [comment]
Ok, thanks for clarifying so we seem to have the same understanding of what I mean. I guess then the problem must be on my side and I don't understand the concept of edit / save buttons in odoo. May I ask what the intention behind this behavior is?

**Comment by pedrobaeza** [comment]
When pressing a button, there's an automatic save operation before the execution of the button, so it's a nonsense to be on edit mode when in reality, you have already saved pressing the button. Adding a set is not undoable operation that you can discard pressing the corresponding button.

**Comment by technicomp** [comment]
Ok, I get you. I was looking at it more from a users point of view when opening an existing SO -I would not expect being able to make changes to the sales order without previously pressing the "edit" button. What I would have expected from the users point of view is that the button simply doesn't show up as long as I am not in edit mode. But I am quite new to Odoo and some thing seem to be a little different. Thank you for taking the time to explain in detail!
