### ISSUE TITLE
[RFC] sale_tax_us: Avalara Tax Connector

### ISSUE THREAD

**Issue by lasley** [OCA/sale-workflow#435]
This module will provide tax calculations via the [Avalara Tax Rates API](http://taxratesapi.avalara.com/docs). Odoo Enterprise currently supports this, but Community was left to fend for themselves. Luckily, that's where OCA comes in!

It will hide the existing Avalara tax option in the Odoo UI, and add an identical checkbox - but for the community version. When checked, a field will be provided to input the API key.

A `tax_state_ids` m2m will be added to `res.company`, which will allow for a whitelist of taxes by state.

It will override the `sale.order.action_confirm` method. If the delivery address is in a taxable state- place a call to the API with that address. The API returns a data structure similar to:

```
{
    "totalRate": 0.086000,
    "rates": [
        {
            "rate": 0.021000,
            "name": "WA CITY TAX",
            "type": "city"
         },
         {
             "rate": 0.065000,
             "name": "WA STATE TAX",
             "type": "state"
         }
    ]
}
```

The existing tax `account.tax` entries will then be searched and updated if necessary. They will then be added to the `sale.order.line.tax_id` m2m.

Fairly simple for the most part. Does anyone have any comments, or recommendations of code to base on?

**Comment by fhe-odoo** [comment]
Regarding your first paragraph:
1. Odoo Enterprise does not support Avatax (are you confused with Taxcloud?).
2. Odoo Community (v7, v8, and v9) supports Avatax, see https://www.odoo.com/apps/modules/browse?search=avatax

So it doesn't seem like Odoo Community is left to fend for itself.

**Comment by lasley** [comment]
Thanks for the response @fhe-odoo. Interesting so yeah in my head the two solutions, Taxcloud & Avatax, were one in the same. I saw that the Avatax one was by Odoo SA, but I didn't see it in the community code, so I immediately correlated it to the existing EE feature.

Would you have any reservations to me bringing your connector to OCA for v10?

**Comment by fhe-odoo** [comment]
@lasley You can do anything you'd like that respects the LGPL3 license of this module. I don't think you can transform LGPL code into AGPL (especially considering the virality level of AGPL), and OCA only accepts AGPL-licensed code if I'm not mistaken (to check).

**Comment by lasley** [comment]
@fhe-odoo - yeah I know I can do anything in regards to the license, I was just more wondering where you'd like to keep the code. I'm assuming because it's in your repo, you wrote it? Figured if you wanted to keep it there, I would just upgrade it there. 

OCA accepts any GNU license, so LGPL is not a problem. It's actually my preferred to be honest.

**Comment by fhe-odoo** [comment]
@lasley  Up to you, you can copy and upgrade to v10 in an OCA repo if that helps (but not sure you can keep the v10 under the same module umbrella than v9 on Odoo Apps since repos are owned by different people).

**Comment by lasley** [comment]
@fhe-odoo - We can definitely keep it under the same umbrella. We've had this happen accidentally  - which kind of sucks, but it's quite cool when we coordinate it correctly. Basically migrating it into OCA would be us taking over maintenance of it going forward. When on the Apps store, the author & repo just dynamically updates as you change versions.

So sounds like a plan then, my team will migrate this in the next few weeks. Thanks for dropping a line!

**Comment by pedrobaeza** [comment]
@lasley This should be hosted in OCA/l10n-usa, not here.

**Comment by bistaray** [comment]
@lasley - are you still planning on doing this - we just had a prospect ask if AvaTax was supported at v10 and it would be great if we could pass on accurate information about plans for a port (or not, as the case may be).

**Comment by lasley** [comment]
@bistaray - We are. I performed some migration steps during my scoping in [this branch](https://github.com/LasLabs/l10n-usa/tree/release/10.0/avatax_connector), and the rest of the work is scheduled two sprints from now.

**Comment by max3903** [comment]
:+1: To move it to https://github.com/OCA/l10n-usa

**Comment by bistaray** [comment]
I agree to move this.

@lasley - any update on the completion status?

**Comment by lasley** [comment]
@bistaray - there was a lot of functionality in the module that did not work + a lot of missing tests, so progress is slow going. We are working on it [here](https://github.com/LasLabs/l10n-usa/tree/release/10.0/avatax_connector), but priority is low.

cc @obulkin

**Comment by lasley** [comment]
We've decided to entirely scrap the Avatax module, and Avatax in general. The provider we have now chosen is TaxJar, and a PR is available https://github.com/LasLabs/odoo-connector-taxjar/pull/1 for an initial version. Closing this
