### ISSUE TITLE
sale_order_revision not working for copied sale order

### ISSUE THREAD

**Issue by ch-aurich** [OCA/sale-workflow#438]
Today I found a bug in sale_order_revision. Here is what we are experiencing:
- copy an existing sale order (our sales department does this quite regularly to avoid to add all positions to a sale order if it is similar than an existing one): original: SO25613 / copy: SO25699
- change the sale order to the new order we received (SO25699)
- confirm the new sale order (SO25699)
- abort the sale order (SO25699)
- try to create a new revision (SO25699)
- an error appears: "Order Reference and revision must be unique per Company."

I had a look at the entry in table sale_order and found out that name (SO25699) is not identical with unrevisioned_name (SO25613).

I fixed the problem by making sale_order.name and sale_order.unrevisioned_name the same - then the problem did not occur anymore.

Environment:
- Odoo 8
- sale_order_revision up to date (branch 8.0)

**Comment by ch-aurich** [comment]
I am not too familiar with odoo programming, but I suspect that function copy in sale_order_revision/model/sale_order.py needs an additional branch that sets the "unrevisioned_name" field in case it is a simple copy and not a "self.env.context.get('new_sale_revision')" copy...

**Comment by bodedra** [comment]
IMO these issue will be resolve by https://github.com/OCA/sale-workflow/commit/4313542c29e33a6e5e21e8ba78219fec067ffb57 OR https://github.com/OCA/sale-workflow/commit/102be6883f7373ab4a7ba142016405c93cad6663#diff-4b32658304249c7a43f23232de5e9f6a

**Comment by pedrobaeza** [comment]
It seems so. Closing.

**Comment by ch-aurich** [comment]
Yes, I can confirm that it works now. Thanks for the hint.
