### ISSUE TITLE
Sale Team Security Rule for res.partner

### ISSUE THREAD

**Issue by aek** [OCA/sale-workflow#442]
I have done this rule to restrict res.partner in v9 based on the sale.team and I get some issues in some specific actions like user preference and the opportunities menu and I get it solved by adding permission to the partner of the current user in the domain of the rule. I think that the same could be happening on the module:
https://github.com/OCA/sale-workflow/tree/8.0/sales_team_security
My rule is:
```xml
<field name="domain_force">['|',('id','=',user.partner_id.id),'&amp;',('team_id','=', user.sale_team_id.id),('team_id','!=', False)]</field>
```
without the ('id','=',user.partner_id.id) part you will get errors in at least those 2 actions

**Comment by pedrobaeza** [comment]
Please try on runbot to confirm and if so, make a PR solving it.

**Comment by aek** [comment]
It's working ok for v8, my issue was with v9

**Comment by pedrobaeza** [comment]
But isn't the module also in v9?

**Comment by aek** [comment]
No, it doesn't

**Comment by pedrobaeza** [comment]
Ok
