### ISSUE TITLE
RFC - Global discount on sale order and invoice

### ISSUE THREAD

**Issue by sebastienbeau** [OCA/sale-workflow#444]
# Aim
- having the possibility to add manually a global discount on the sale order or invoice (percentage or amount)
- being a based module for a cart discount rule module. A cart discount rule can be cumulative or not and will add one or more global discount on the sale order / invoice

# Implementation

```
class AbstractDiscountLine
    fields:
        - discount_type (percentage/amount)
        - value


class SaleDiscountLine
     _inherit = 'abstract.discount.line'
     fields:
        - sale_id

class InvoiceDiscountLine
     _inherit = 'abstract.discount.line'
     fields:
        - invoice_id

```

When adding a discount line on a sale order. We automatically add one or more hidden sale_order_line with a special product. The number of line added will depend of the taxes to apply.
Example (French Company)
- One sale order with 2 lines. First line with a product taxed at 5.5% and a subtotal of 10 € (tax inc) and the second line with a taxed at 20% and a subtotal of 20€ (tax inc)
- A global discount of 3€
=> in that case we should add 2 sales order lines. One with 1€ with a taxed included of 5.5% and one line with 2€ with a taxed included of 20%

If you update the sale order line (price, qty, adding a new line...) the automatic generated sale order line should be updated if needed.

The discount line added on a sale order should be passed to the related invoice.

In the same way the discount line have added hidden line on the sale order, the discount line will add hidden line on the invoice. When we validate the invoice, the move generated will take in account the discount as discount exist as invoice line, so we do not need to modify the code that generate the account move.

What do you think ?

**Comment by pedrobaeza** [comment]
You should also treat the transfer to invoice and the accounting treatment.

**Comment by sebastienbeau** [comment]
Yes, this is why we add sale order line so there are already transfert to the invoice and process in accounting

**Comment by sebastienbeau** [comment]
@pedrobaeza I have updated the description

**Comment by bealdav** [comment]
:+1:

**Comment by lfreeke** [comment]
:+1:

**Comment by fclementic2c** [comment]
@sebastienbeau Yes are right about the VAT. Invoicing will follow even if multiple invoices. Ok on the principle.

**Comment by elicoidal** [comment]
:+1:

**Comment by zakiuu** [comment]
👍

**Comment by pedrobaeza** [comment]
This has been implemented in https://github.com/OCA/sale-workflow/tree/13.0/sale_global_discount
