### ISSUE TITLE
Asking to submit new addon - Split Quotation and Sales Order (as separate document)

### ISSUE THREAD

**Issue by kittiu** [OCA/sale-workflow#448]
Hi,
I would like to submit our frequently used module, sale_split_quote2order.
Are there similar module already exists, and/or will this module be useful enough to be in OCA?
Here the link, now is for v8.
https://github.com/pabi2/pb2_generic/blob/master/sale_split_quote2order

**Short Description:**
This module separate quotation and sales order by adding type (quotation, sale_order) in sale.order.
During Quotation, a new "Conver to Order" button. Once converted, the draft Sales Order will be created with new number. Quotation will reduce to have only 2 state, Draft and Done. Sales Order will then fall in to normal process.

Thank you,

**Comment by pedrobaeza** [comment]
I don't think so. Just follow guidelines and make the PR. Maybe the name should be changed, as quote2order implies a transformation. Maybe sale_isolated_quotation?

**Comment by kittiu** [comment]
@pedrobaeza , ok, the "sale_isolated_quotation" is fine. We will start working on it, and will do the PR once we finish.

Thanks!

**Comment by kittiu** [comment]
The module is ready for review. Thank you!
https://github.com/OCA/sale-workflow/pull/457
