### ISSUE TITLE
[RFC] sale_calendar_resource: Selling Calendar Event Resources

### ISSUE THREAD

**Issue by lasley** [OCA/sale-workflow#452]
This module will provide the ability to sell resource allocations, which can be used for purposes such as medical appointment scheduling. 

[product_service_duration](https://github.com/OCA/product-attribute/pull/251) will be a dependency, which adds a relation to `resource.resource` on `product.template`.

A `calendar_event_id` field will be added to `sale.order.line` to relate a line to a specific calendar event for it. It will have a context to default the event to the partner for the sale and the product, and to add the product to the event. The event will be created as a draft.

A `pricelist_id` field will be added to `calendar.event`.

We will hook into the `action_confirm` method of the sale, which will subsequently confirm any events associated with the sale. The event `pricelist_id` will also be updated to correspond with the sale `pricelist_id`.

[calendar_resource](https://github.com/OCA/crm/pull/135) will be added as a dependency, which will provide the necessary glue between resources and events. It also provides handling for double booking.

Invoicing can then take place over the standard methods, although I will be submitting another RFC soon that will bind invoicing directly to the events, in order to allow alteration of what products were actually serviced during the event.

**Comment by lasley** [comment]
@jbeficent - this was another piece of the `medical_appointment` upgrade/billing

@dreispt - you might be interested too

**Comment by dreispt** [comment]
I have no direct interest in this feature but, since its being abstracted away form medical appointments, it's relevant to identify other possible use cases, to be taken in account.
I can think of: sell tickets from specific places (cinema, event room chairs); sell numbered places in transportations (trains, buses, ...).

**Comment by lasley** [comment]
In the instances of selling tickets to specific or numbered places - would each "place" (bus seat, stadium seat, etc) be considered a resource of its own?

**Comment by dreispt** [comment]
Yes. It may sound an overkill in case the "seat" numbers are lenar, but in many cases they aren't:
think about resort hotels, for example.

**Comment by lasley** [comment]
Sweet that makes perfect sense. Even in the case of linear, there could be instances in which a resource is not available but the other ones are - Maybe the chair broke or something.

**Comment by dreispt** [comment]
Yes, good point.
