### ISSUE TITLE
Sale Lot Selection

### ISSUE THREAD

**Issue by colmed** [OCA/sale-workflow#467]
sale lot selection module not working properly with existing database, it will through the error when click on **confirm sale** and error is **TypeError: _prepare_procurement_from_move() takes exactly 2 arguments (1 given)**
can any buddy help me resolve this problem

**Comment by yostashiro** [comment]
Haven't got the time to further follow up, but I made a PR for this issue: https://github.com/OCA/sale-workflow/pull/460
