### ISSUE TITLE
Question: Should we mark addon from Unported section, given it will is no longer relevant for an Oodo version?

### ISSUE THREAD

**Issue by kittiu** [OCA/sale-workflow#490]
If some modules are no longer relevant from v8 to v10 version of Odoo, especially when there are big changes in the data structure. Should we notify the project maintainer and/or should be marked or removed from this table?
https://github.com/OCA/sale-workflow#unported-addons

**Comment by pedrobaeza** [comment]
If there are modules that no longer be needed on a new version, just make a PR removing them, and they will be also auto-removed from the table next time the update script will auto-run.

**Comment by rafaelbn** [comment]
This cases are mainly modules that in new versions are included in Odoo core. @kittiu Which modules do you mean ? Thanks 😄

**Comment by kittiu** [comment]
@rafaelbn for example, I came across, https://github.com/OCA/hr/tree/10.0/hr_expense_invoice
This one, (I think), is used to via expense to supplier. But since, the v10 already have feature to pay expense to supplier, plus expense model now is completely revamped, so to me it is not required to upgrade.
Sorry, my example is not in sale-workflow.
What @pedrobaeza is well understood and I will do that next time.
