### ISSUE TITLE
Migration from launchpad

### ISSUE THREAD

**Issue by eLBati** [OCA/sale-workflow#5]
- Point 5: https://github.com/OCA/maintainers-tools/pull/24
- Point 6:
  - https://github.com/OCA/sale-workflow/pull/6
  - https://github.com/OCA/sale-workflow/pull/7

**Comment by eLBati** [comment]
I can do points 5, 6, and 8.
I need a maintainer for points 3, 4, 9, 10

**Comment by pedrobaeza** [comment]
OK, I'll do it.

As usual, we'll set 8.0 branch when we make 7.0 PEP8 fix.

**Comment by pedrobaeza** [comment]
Done!

Step 9 still requires an OCA board member to modify it, and step 7 and 10 must be done after the PEP8 fix.

Regards.

**Comment by eLBati** [comment]
I'm starting to fix PEP8 of 7.0 branch :smirk:

**Comment by pedrobaeza** [comment]
Cool! I'll be watching for review.

**Comment by eLBati** [comment]
The PR https://github.com/OCA/sale-workflow/pull/10

**Comment by pedrobaeza** [comment]
And here is the step 7 : #11.

**Comment by gurneyalex** [comment]
both 10 and 11 and done. Can we close this?

**Comment by pedrobaeza** [comment]
I think so.

Regards.
