### ISSUE TITLE
Sale Order Revision - Lines not canceled

### ISSUE THREAD

**Issue by JuaniFreedoo** [OCA/sale-workflow#508]
When doing an order review, order is cancelled and also  lines should be,  but instead,  when generating order lines information  they are still listed.

**Comment by bodedra** [comment]
@FreeDoo2018 IMO you should provide more details on your issues like which version of Odoo are you using ? Are you able to reproduce it on runbot ? That will help us to review it.

**Comment by bodedra** [comment]
We can close these issues due to lack of information.
