### ISSUE TITLE
Should we revert 5891bdc37e24cf31fde19ea9eb8413848069a57a

### ISSUE THREAD

**Issue by nbessi** [OCA/sale-workflow#52]
https://github.com/OCA/sale-workflow/commit/5891bdc37e24cf31fde19ea9eb8413848069a57a
commit add a new dependence on an other OCA repo on a stable module without changing version.

This may break existing instances and raise a question about OCA merge acceptance rules.
Should we accept a PR that add a dependence on external repo on an existing module?

Regards

Nicolas

**Comment by lepistone** [comment]
(I paste here my comment on the commit)

I fully agree we should increase the version substantially. If we had changelogs, it should be noted there. We could add an annotation in the manifest anyway.

As reverting altogether, that seems a bit drastic. Let's hear what the others say.

Thanks @nbessi for bringing this up.

**Comment by pedrobaeza** [comment]
Well, we talked that an outside dependency must not be allowed in OCA, but there is no PR for that module?

**Comment by nbessi** [comment]
@pedrobaeza I updated my comment it is based on an other OCA repo but on a stable module

**Comment by pedrobaeza** [comment]
Ah, OK. In this case I think we can do it, because it's very easy to fix installations with this module (add dependency and install it without making update=all, and then update the other module), but we should warn it on module manifest and on commit message.

**Comment by gurneyalex** [comment]
@nbessi what is the status of this?

**Comment by gdgellatly** [comment]
I am fairly sure this issue is decided. If not, it never will be.
