### ISSUE TITLE
last_sale_price would be better named sale_last_price

### ISSUE THREAD

**Issue by clonedagain** [OCA/sale-workflow#53]
I think it would be closer to the convention of having the main "app" as the first word in the module name.

**Comment by pedrobaeza** [comment]
I also agree with @clonedagain.

**Comment by yvaucher** [comment]
I suggest to target the name change on 8.0

**Comment by clonedagain** [comment]
@yvaucher yes that looks sane.
Maybe the name should actually be sale_latest_price - can a native English speaker confirm please?

**Comment by rafaelbn** [comment]
this is already solved
