### ISSUE TITLE
Product quantity in the invoice is always the same as the original sale order  

### ISSUE THREAD

**Issue by BusinessTec** [OCA/sale-workflow#545]
module: sale_partial_invoicing
version: 8.0

**Steps to reproduce**
- create sale order
- create invocie, select lines of sale order
- select any line in sale order and modify qty to make it lower then that of SO
- view invoice draft

**Current behavior**
Product quantity in the invoice line is the same as in the sale order
**Expected behavior**
Product quantity in the invoice line is the same as entered in the partial sale wizard

Using  the module version from:
https://github.com/rosenvladimirov/addons/tree/8.0/sale_partial_invoicing

**Comment by pedrobaeza** [comment]
That's not the official OCA addon, so it can be because of that. Closing this.
