### ISSUE TITLE
[10.0][sale_order_revision] Order Reference and revision must be unique per Company.

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/sale-workflow#557]
Hi,

The error 'Order Reference and revision must be unique per Company.' constantly appears in runbot, and totally prevents a user from confirming new orders.

Not sure yet why this happens, but it is very annoying in this repo.

**Comment by LoisRForgeFlow** [comment]
Just found the same issue while reviewing https://github.com/OCA/sale-workflow/pull/572#issuecomment-346877482

**Comment by pedrobaeza** [comment]
Is this still happening?

**Comment by LoisRForgeFlow** [comment]
I guess not, but I got a different one while checking on the runbot:

```
Uncaught Error: Unknown field is_template in domain [["is_template","=",true]]
```
The error raises when trying to save a sales order. I think it is related to `sale_generator`

**Comment by pedrobaeza** [comment]
Yeah, it can be...

Closing this issue. Feel free to open another for the other problem.
