### ISSUE TITLE
[10.0] New feature: blanket sales order management

### ISSUE THREAD

**Issue by Cedric-Pigeon** [OCA/sale-workflow#592]
One of my customers needs to manage blanket sales orders. I cannot find any thing fitting my needs neither in core neither in OCA. So I am planning to implement a new simple module.

My idea is to create a new object "Blanket Order" with these attributes:

- Customer
- Pricelist
- Payment terms
- Validity date
- State (Draft, Opened, Expired)
- List of products with proposed quantity and price

The workflow is:

1. Blanket Order Creation 
The user encodes the blanket order and once he finds an agreement with the customer, he confirms it

2. Consumption of quantities
Once it is confirmed, a wizard is available to generate sale orders. The user can select the product in the list and set the ordered quantity, which can not exceed the blanket order quantity.

3. End of validity

If all proposed quantities has been consumed, no new sale order can be created.
If the validity date is past, the blanket sale orders jump to "Expired" state whatever all quantities are consummed or not

At all moment, the user can know for all products:

- the original quantity
- the ordered quantity
- the delivered quantity
- the invoiced quantity

and can access to linked sales orders.

Does anyone has on opinion on my suggestion ?

**Comment by sbidoul** [comment]
This reminds me of this thread.

https://odoo-community.org/groups/contributors-15/contributors-60794

**Comment by Cedric-Pigeon** [comment]
Indeed there are similarities except for the recurring part.
On a blanket Order, the customer decides to order/consum whenever he wants.

**Comment by pedrobaeza** [comment]
Closing as there is now an opened PR.
