### ISSUE TITLE
[8.0] sale_rental installation error and fix

### ISSUE THREAD

**Issue by gentooza** [OCA/sale-workflow#598]
Hi!

we couldn't install sale_rental in our odoo 8.0 with an import rental.py error.

so we noticed it had in it' s __init__.py:
`from . import rental`
when it should be:
`import rental`
as rental appears to be in the root folder of the module.

for us now it's working
cheers!

**Comment by pedrobaeza** [comment]
No, that's called a relative import, and it's correct. The problem is in your deployment method and PYTHONPATH you are using.
