### ISSUE TITLE
Project/Tasks created from a SO

### ISSUE THREAD

**Issue by benwillig** [OCA/sale-workflow#612]
**Version: 11.0**

A project can be created during the sale confirmation if the order lines contains a service product with the proper configuration. Sometimes, even if the SO has not been officially confirmed, some work is done and you want to track your employee's timesheets. But you can't do that because you have to confirm the SO. The idea would be to allow users to create the project/tasks related to the order lines even if the SO is in draft.

**Proposed design:**

- Add a button on the SO which simply creates the project and tasks
- ~~Forbid to delete a SO line if the linked task has timesheets~~ (Edit: do not forbid it, keep the odoo base workflow)

**Issues:**

- When the SO is in draft, you can manually link an analytic account. Should we set this field to readonly when the project/tasks have been created before the SO confirmation
- If the project/tasks are created before the SO confirmation, their names don't contain the SO number. So we should implement a mechanism which readd the SO number in the ```name_get``` or in the ```name```  field after the sale confirmation.

Edit: https://github.com/OCA/sale-workflow/pull/614

**Comment by benwillig** [comment]
cc @sbidoul @phschmidt

**Comment by sbidoul** [comment]
:+1: This is useful in situations when work on project must be done in anticipation of the order confirmation.

> When the SO is in draft, you can manually link an analytic account. Should we set this field to readonly when the project/tasks have been created before the SO confirmation

I think we should not add additional constraints of this kind (unless the data becomes corrupted as inconsistent as a result of changing it).

Basically, this module should more or less do the same behaviour as confirm/reset to draft/confirm wrt project and task creation.
