### ISSUE TITLE
Module sale_triple_discount: 1 failures, 0 errors in test Travis-ci

### ISSUE THREAD

**Issue by apesquero** [OCA/sale-workflow#629]
Hello, testing my module, I'm seeing that in "travis" I see an error related to sale_triple_discount, which has no relation to my module.
https://travis-ci.org/OCA/sale-workflow/jobs/363434923

On the other hand,

I have also verified that within runbot there are problems in putting products in the line items related to the error:

Unknown field is_template in domain [["is_template", "=", true]]

Thank you.

**Comment by apesquero** [comment]
Making a few simple changes and reversing those changes, to leave it as it was, now does not give problems the test sale_triple_discount.
https://travis-ci.org/OCA/sale-workflow/jobs/363471961

What could be the reason why it did not work the first time?

Thank you.

**Comment by pedrobaeza** [comment]
Closing as no real problem.
