### ISSUE TITLE
[10.0][sale_generator] Unable to create sale order lines

### ISSUE THREAD

**Issue by AaronHForgeFlow** [OCA/sale-workflow#630]
Cannot create sale order lines on any sale-workflow runbot v10. There's some problem with the sale view. The error message:

![image](https://user-images.githubusercontent.com/19620251/38604334-4e3d7080-3d70-11e8-8038-01ac04436347.png)

The module that introduces that domain to the sale views is sale_generator. After first installed the module no issues were found. However, after uninstalling the module, some domains remain.

**Comment by bealdav** [comment]
Ok, I have to fix it

**Comment by LoisRForgeFlow** [comment]
@bealdav This keeps happening and is very annoying, could you please have a look?

**Comment by bealdav** [comment]
Yes I searched, but I can't to reproduce the problem, in my workstation for now

**Comment by bealdav** [comment]
OK, strange weird unpredictible behavior. But now convinced that unpredectiblable behavior not caused by other module in branch.

I'll focus now on sale_generator.

**Comment by bealdav** [comment]
@lreficent please could you rebuild the branch because impossible to reproduce this bug elsewhere.

Thanks

**Comment by rafaelbn** [comment]
@aheficent it looks this is solved as I have tried and it works. Take a look in: http://3325894-10-0-0674d6.runbot2.odoo-community.org/web#id=12&view_type=form&model=sale.order&menu_id=210&action=282

**Comment by rafaelbn** [comment]
Hi @bealdav ! Here you are: http://3326177-10-0-0674d6.runbot1.odoo-community.org/web?debug

`Error: Unknown field is_template in domain [["is_template","=",true]]`

```
http://3326177-10-0-0674d6.runbot1.odoo-community.org/web/content/549-8252a30/web.assets_backend.js:1767
Traceback:
compute_domain@http://3326177-10-0-0674d6.runbot1.odoo-community.org/web/content/549-8252a30/web.assets_backend.js:1767:42
compute_domain@http://3326177-10-0-0674d6.runbot1.odoo-community.org/web/content/549-8252a30/web.assets_backend.js:2188:339
init/<@http://3326177-10-0-0674d6.runbot1.odoo-community.org/web/content/549-8252a30/web.assets_backend.js:2222:341
trigger@http://3326177-10-0-0674d6.runbot1.odoo-community.org/web/content/543-300e47e/web.assets_common.js:3104:166
trigger@http://3326177-10-0-0674d6.runbot1.odoo-community.org/web/content/543-300e47e/web.assets_common.js:3108:115
on_form_changed@http://3326177-10-0-0674d6.runbot1.odoo-community.org/web/content/549-8252a30/web.assets_backend.js:2138:93
load_record/<@http://3326177-10-0-0674d6.runbot1.odoo-community.org/web/content/549-8252a30/web.assets_backend.js:2135:1
then/</</<@http://3326177-10-0-0674d6.runbot1.odoo-community.org/web/content/543-300e47e/web.assets_common.js:547:678
fire@http://3326177-10-0-0674d6.runbot1.odoo-community.org/web/content/543-300e47e/web.assets_common.js:541:281
add@http://3326177-10-0-0674d6.runbot1.odoo-community.org/web/content/543-300e47e/web.assets_common.js:542:467
then/</<@http://3326177-10-0-0674d6.runbot1.odoo-community.org/web/content/543-300e47e/web.assets_common.js:547:631
each@http://3326177-10-0-0674d6.runbot1.odoo-community.org/web/content/543-300e47e/web.assets_common.js:370:758
then/<@http://3326177-10-0-0674d6.runbot1.odoo-community.org/web/content/543-300e47e/web.assets_common.js:547:553
Deferred@http://3326177-10-0-0674d6.runbot1.odoo-community.org/web/content/543-300e47e/web.assets_common.js:548:189
then@http://3326177-10-0-0674d6.runbot1.odoo-community.org/web/content/543-300e47e/web.assets_common.js:547:518
load_record@http://3326177-10-0-0674d6.runbot1.odoo-community.org/web/content/549-8252a30/web.assets_backend.js:2134:382
trigger@http://3326177-10-0-0674d6.runbot1.odoo-community.org/web/content/543-300e47e/web.assets_common.js:3104:166
trigger@http://3326177-10-0-0674d6.runbot1.odoo-community.org/web/content/543-300e47e/web.assets_common.js:3108:115
load_defaults/<@http://3326177-10-0-0674d6.runbot1.odoo-community.org/web/content/549-8252a30/web.assets_backend.js:2137:198
then/</</<@http://3326177-10-0-0674d6.runbot1.odoo-community.org/web/content/543-300e47e/web.assets_common.js:547:678
fire@http://3326177-10-0-0674d6.runbot1.odoo-community.org/web/content/543-300e47e/web.assets_common.js:541:281
fireWith@http://3326177-10-0-0674d6.runbot1.odoo-community.org/web/content/543-300e47e/web.assets_common.js:546:198
Deferred/</deferred[tuple[0]]@http://3326177-10-0-0674d6.runbot1.odoo-community.org/web/content/543-300e47e/web.assets_common.js:548:31
fire@http://3326177-10-0-0674d6.runbot1.odoo-community.org/web/content/543-300e47e/web.assets_common.js:541:281
fireWith@http://3326177-10-0-0674d6.runbot1.odoo-community.org/web/content/543-300e47e/web.assets_common.js:546:198
then/</</<@http://3326177-10-0-0674d6.runbot1.odoo-community.org/web/content/543-300e47e/web.assets_common.js:547:849
fire@http://3326177-10-0-0674d6.runbot1.odoo-community.org/web/content/543-300e47e/web.assets_common.js:541:281
fireWith@http://3326177-10-0-0674d6.runbot1.odoo-community.org/web/content/543-300e47e/web.assets_common.js:546:198
then/</</<@http://3326177-10-0-0674d6.runbot1.odoo-community.org/web/content/543-300e47e/web.assets_common.js:547:849
fire@http://3326177-10-0-0674d6.runbot1.odoo-community.org/web/content/543-300e47e/web.assets_common.js:541:281
fireWith@http://3326177-10-0-0674d6.runbot1.odoo-community.org/web/content/543-300e47e/web.assets_common.js:546:198
done@http://3326177-10-0-0674d6.runbot1.odoo-community.org/web/content/543-300e47e/web.assets_common.js:937:86
callback@http://3326177-10-0-0674d6.runbot1.odoo-community.org/web/content/543-300e47e/web.assets_common.js:957:15
```

**Comment by rafaelbn** [comment]
Hi again @bealdav it looks like `sale_generator` is the problem.  because after uninstalling It I can add line to SO

**Comment by EBII** [comment]
hello it is just a workaround to find residual domain after uninstall sale_generator

use sql query to find id 
select name,domain,id from ir_act_window where domain like '%is_template%';
it looks like that
db=# select name,domain,id from ir_act_window where domain like '%is_template%' ;
    name    |                     domain                     | id  
------------+------------------------------------------------+-----
 Quotations | [('state', 'in', ('draft', 'sent', 'cancel')),+| 244
            |             ('is_template', '=', False)]      +| 
            |                                                | 
(1 row)
you may update or delete these row 

i can not reproduce what i saw on run bot locally with can not add row on SO with sale_generator installed, with client side error message : 
 Error: Unknown field is_template in domain [["is_template","=",true]]

**Comment by rousseldenis** [comment]
@bealdav @rafaelbn @EBII I think I've already had this kind of problem. Due to priority on inherited form.

**Comment by bealdav** [comment]
OK. May be we might put a priority to test. Thanks

**Comment by rousseldenis** [comment]
@bealdav what I wanted to say that there is a priority on https://github.com/OCA/sale-workflow/blob/f2e9fb70592d214c5cc55530cfbc2bade8c4848a/sale_generator/views/sale_view.xml#L6

Sometimes, removing it solves the problem.

**Comment by rafaelbn** [comment]
Hi @rousseldenis @aheficent @bealdav we have in runbot still this issue as I said in https://github.com/OCA/sale-workflow/issues/630#issuecomment-389357396 and this makes a headache eveytime anyone need to test a single PR... please who could solve it? Please! :smile:

**Comment by MiquelRForgeFlow** [comment]
@rafaelbn This issue was solved  😉

**Comment by pedrobaeza** [comment]
Where? Can we close it then?

**Comment by AaronHForgeFlow** [comment]
I could not reproduce the issue here: https://github.com/OCA/sale-workflow/pull/668 So I guess this was fixed. I'm closing this, feel free to reopen if this is not really fixed.

**Comment by scaldewi** [comment]
Hi, seems issues were fixed, but still module is installable: False in 10.0 branch.
And no attempt to migration for 11.0. 
Can u help me understand reason for this? Would be interested in migrating to 11.0

**Comment by bealdav** [comment]
I was unable to reproduce error on my side.

I think, you can port to v11.

Integration made by installation of different set of modules can lead to different result in v11.

If you get additionnal information on this topic, we could fix v10 branch

Thanks
