### ISSUE TITLE
Incompatibility between sale_isolated_quotation  and sale_order_revision Odoo 10.0

### ISSUE THREAD

**Issue by vinclar** [OCA/sale-workflow#634]
Steps to reproduce:
- Create a quotation and select "Convert to Order"
It returns validation error "Order Reference and revision must be unique per Company."

**Comment by pedrobaeza** [comment]
Yeah, by their nature, they will probably collapse together. If you have a patch for solving the incompatibility, please provide a PR.

**Comment by hcbayram** [comment]
Hi,
I inherit sale.order as below and it solved the issue.

class saleorderInherit(models.Model):
    _inherit ="sale.order"
    def _prepare_order_from_quotation(self):
            res = super(saleorderInherit, self)._prepare_order_from_quotation()
            res.update(
                unrevisioned_name= res['name'],
                revision_number = 0,
                current_revision_id= None,
            )
            return res
