### ISSUE TITLE
#11 Menu 'sale_exception' path: 'sale_exception/views/sale_view.xml'

### ISSUE THREAD

**Issue by awa-si** [OCA/sale-workflow#641]
CURRENT: 
========
       <menuitem
                id="menu_sale_exception_parent"
                parent="sales_team.menu_sale_config"
                sequence="20"
                name="Exceptions"
        />

SHOULD BE:
========
        <menuitem
                id="menu_sale_exception_parent"
                parent="sale.menu_sale_config"
                sequence="20"
                name="Exceptions"
        />

**Comment by pedrobaeza** [comment]
Why this change?

**Comment by awa-si** [comment]
Module 'sale_exception' inherits 'sale' and menu entry 'menu_sale_config' is its property.

**Comment by bodedra** [comment]
IMO these issue has been taken care at https://github.com/OCA/sale-workflow/blob/11.0/sale_exception/views/sale_view.xml#L17 So we are good to close it.

PR reference https://github.com/OCA/sale-workflow/pull/719
