### ISSUE TITLE
RFC: Multiple sale orders for one quotation

### ISSUE THREAD

**Issue by thomaspaulb** [OCA/sale-workflow#660]
Our client has the following use case: he quotes his customer a total of 10 items, then when sold, wishes to continue with each of the 10 as an isolated sale order, because these sales typically take a long time and also have other logic attached to it which makes it better to handle separately.

So he wishes, on confirmation of a quotation, to be able to split the quotation into separate sale orders.

This requirement is related to [sale_isolated_quotation](https://github.com/OCA/sale-workflow/pull/457), but with a different [reason](https://github.com/OCA/sale-workflow/pull/457/commits/de8d1aca5b71f22a657866d8e7f3831cee9d6506) and with of course a many2one relationship from Quotation to Saleorder.

My design of this would amount to the following:

1. Create a one2many relationship between `sale.order` and, well, `sale.order`, calling it e.g. `sale_order_ids`. In the form view of quotation, show this in the top right corner as square widget with which to click through to the related sale orders. Make the numbering of these dependent sale orders logical by adding something like `-01`, `-02` or perhaps `P01` to distinguish from those created by `sale_order_revision`.
2. On quotation, add a button "Create Sale Orders" which opens a wizard that handles the split
3. The workflow to change such that after executing the wizard, the quotation is set to "Done" and the new sale orders are in "Draft".
4. The wizard to have an Integer field specifying the amount of sale orders to divide the sale order lines over, and a readonly embedded List view reminding the user of the quotation lines he is about to split.
5. Some warnings for when users select weird split numbers

An extension of this idea could be to also allow partial splitoffs:

1. The wizard to show a tree view with for each order line the product/description/price/qty (read only), and a checkbox and a splitoff qty (editable). The splitoff qty could default to the number of items for that product on the quotation MINUS the ones already handled in previous related sale orders. 
2. The wizard to still have an Integer field for the number of "over how many sale orders to divide" the quantities selected on the lines below, defaulting to "1.0"
3. The workflow being such that the quotation moves to "Done" if all of the quotation lines have been fully allotted to sale orders, and a "Force Done" button that can shortcut the workflow and appears only when at least one sale order has been created.

Questions:
@kittiu Could this be a useful extension of the `sale_isolated_quotation` module? Do your customers sometimes ask for one quotation becoming several sale orders?
@elicoidal @lreficent @pedrobaeza @hbrunn Care to comment on this idea?

**Comment by elicoidal** [comment]
LGTM mostly with the wizard with partial splitoffs.
We have the same requirement but to create PO from the SOL (typical in the trading business) so a potential spinoff module could be to add a checkbox to create a PO instead of SO (maybe to come in the coming months)

**Comment by hbrunn** [comment]
1. make the suffix/prefix for a dependent order a sequence, then the user can configure this as she likes
2. is the wizard really necessary? If we can assume every order line should be its own order, then we could just do this when advancing the parent order's state
3. I think the parent's state should be `pending` until the children are done, then the order is done itself. Without this, I think you lose part of the trick of doing this dance in the first place, as I understand it (following the state of many suborders by looking at the big order).
3.1. Also fields like `invoiced_rate` and `shipped` probably should propagate from the children to parents, maybe that's more for version 2

For your extension I'd provide enough hooks in the workflow so that it's simple to add this in a separate module.

**Comment by thomaspaulb** [comment]
@elicoidal Thanks
@hbrunn 1. Good idea, but is it technically possible to have a sequence with two variables in it and not advance the first one? SO**XXXXX**-P**YY**
2. We cannot assume that, I think splitting needs vary from case to case and it's not always 1 full line
3. That is not true in this case, the original quotation is accepted but then completely replaced by the suborders. It's not necessary to keep the original quotation open or reflecting the children.

**Comment by hbrunn** [comment]
1. no, but you can use some sequence to generate the PYY part, that's what i meant. But then this wont help so much I guess

**Comment by elicoidal** [comment]
> 1.no, but you can use some sequence to generate the PYY part, that's what i meant. But then this wont help so much I guess

At least it makes it configurable (eg: I prefer SOXXXXX-YY)
