### ISSUE TITLE
[10.0] [sale_order_type] billing journal account not set in invoices from sales

### ISSUE THREAD

**Issue by HaraldPanten** [OCA/sale-workflow#682]
module: sale_order_type
version: 10.0

**Steps to reproduce**

1- Create a sale order type --> example 1

2- In example 2, set a billing journal.

3- For the journal in step 2, configure a random account for sales. Imagine: 700001

4- Create a sales order select sale order type --> example 1, and add any product to the sales order lines.

5- Confirm the sales order and create the invocie.

6- The invoice line is not showing account 700001. It's getting the account from the product categories. 

**Current behavior**

Invoice lines are getting the account number from product categories instead of the journal set in sales order types.

**Expected behavior**

When generating the invoice lines, account should be taken from the journal defined in sale type field.

**Comment by pedrobaeza** [comment]
On normal flow (creating manually the invoice and changing the journal), that account is changed?

**Comment by HaraldPanten** [comment]
Hi @pedrobaeza , thanks for your prompt reply.

If I create a new invoice and I change the billing journal, it works as follows:

1- I select a customer, journal, etc.

2- I create a new invoice line --> the line is empty except for the account, it's showing (imagine) 700001.

3- If I add a product, the account changes automatically to 700000.

So... Does it really make sense?

OK, I agree that the default income account should be taken from the product categories (in this case 700000). But, using sale_order_type module, shouldn't take precedence the accounts set for the journal selected on the Sale Type?

Thanks in advance.

**Comment by pedrobaeza** [comment]
Sorry, but I don't think that should be the flow, and it's not implemented right now. If you want to contribute it, I think it should be opt-in, as not everyone wants that behavior.
