### ISSUE TITLE
[RFC] sale_order_display_discount

### ISSUE THREAD

**Issue by Cedric-Pigeon** [OCA/sale-workflow#694]
Hi Folks,

Odoo allows to add a discount in percentage on lines but it directly computes the subtotal with it.
I need a way to have the discount value on each line as well as globally on the sale order.

We will work on a new addon adding the fields discount_total and discount_subtotal on sale.order.line and sale.order.

What do you think ?

**Comment by Cedric-Pigeon** [comment]
@sebastienbeau

**Comment by lmignon** [comment]
@Cedric-Pigeon you mean the price total without discount and the total discount amount.  
Therefore IMO the field names are ambiguous. Why not:  total_without_discount, discount_amount

**Comment by Cedric-Pigeon** [comment]
@lmignon indeed

**Comment by sebastienbeau** [comment]
Let's do it ! :+1:
