### ISSUE TITLE
[10.0] base branch fails sale_mrp_link tests

### ISSUE THREAD

**Issue by SimoRubi** [OCA/sale-workflow#717]
First occurrence of the fail: https://travis-ci.org/OCA/sale-workflow/jobs/436183007#L1789

**Comment by tafaRU** [comment]
@SimoRubi, thanks for reporting the issue.
The fail is due to the installation of `sale_procurement_group_by_line`as explained in https://github.com/OCA/sale-workflow/pull/661#discussion_r214031110

It is necessary to also exclude `sale_delivery_split_date`. I'll give a try in the next days.

**Comment by rafaelbn** [comment]
Solved in https://github.com/OCA/sale-workflow/pull/718

**Comment by tafaRU** [comment]
@rafaelbn, wouldn't be better to close the issue once the linked PR will be merged?
