### ISSUE TITLE
[product_supplierinfo_for_customer_sale] Change functionality from v8 to v10 to v11

### ISSUE THREAD

**Issue by rafaelbn** [OCA/sale-workflow#737]
Hello,

The functionality of the module has change in the migration from v8 to v10 and from v10 to v11 and this impacts to all the customers using this module after a migrations from version to another.

The actual functionality in v11 IMHO is not valid as **in the sale order backend I don't see at all the internal name or the internal code**. I think this is an error that must be fixed.

The **best approach (re-usability**) I think is the v10 actually **because** then this module can be **re-used** for all the variants. If not we have to do 3 different modules as obviously here we have 3 deferent requirements

### Fixes should be done:
- [ ] The column "Product" in the sale order line must be the internal display name  (code + name) as always
- [ ] For the Odoo customers or Odoo integrators which use Portal should FIX the portal (IMHO is an Odoo BUG/IMP) to Show only the "Description" and not the Internal Product fields <--- This shouldn't be fixed in this module

### Reasoning

- Odoo Customer's Users are used to the internal name and the internal code
- Odoo Customer ask for this functionality because the final customer wants it's names and code in the sale order (in v11 this means PDF + Portal)
- Odoo Customer's Users need to see in the backend internal name and the internal code because is imposible to recognize 

### See image:

![product_supplierinfo_for_customer_sale changes from v8-10-11](https://user-images.githubusercontent.com/8736623/48626959-91d6ee80-e9b3-11e8-9cbb-154bb10a6ed4.png)

Odoo v8
- OCA/product-attribute:
  - https://github.com/OCA/product-attribute/tree/8.0/product_customer_code
  - https://github.com/OCA/product-attribute/tree/8.0/product_supplierinfo_for_customer
  - https://github.com/OCA/product-attribute/tree/8.0/product_supplierinfo_for_customer_sale
- OCA/sale-workflow:
  - https://github.com/OCA/sale-workflow/tree/8.0/product_customer_code_sale

Odoo v9
- OCA/product-attribute:
  - https://github.com/OCA/product-attribute/tree/9.0/product_customer_code
- OCA/sale-workflow:
  - https://github.com/OCA/sale-workflow/tree/9.0/product_customer_code_sale

Odoo v10
- OCA/product-attribute:
  - https://github.com/OCA/product-attribute/tree/10.0/product_customer_code
  - https://github.com/OCA/product-attribute/tree/10.0/product_supplierinfo_for_customer
- OCA/sale-workflow:
  - https://github.com/OCA/sale-workflow/tree/10.0/product_supplierinfo_for_customer_sale

Odoo v11
- OCA/product-attribute:
  - https://github.com/OCA/product-attribute/tree/11.0/product_supplierinfo_for_customer
- OCA/sale-workflow:
  - https://github.com/OCA/sale-workflow/tree/11.0/product_supplierinfo_for_customer_sale

Some of the contributors are: @moylop260 @hurrinico @eLBati @oihane @pedrobaeza @ysantiago @nikul-serpentcs @aheficent @mreficent @JayVora-SerpentCS 

What do you think?

Thanks
Regards
Rafael

**Comment by moylop260** [comment]
Hi Rafa,
I'm a little lost here.

Could we just planning 11.0?

I mean, What modules should we split and what functionality each one?

**Comment by moylop260** [comment]
@rafaelbn 
The original odoo module for supplierinfo is working like following cases (After saving purchase show):
 - purchase.product_id <- `[product_id.code] product_id.name`
 - purchase.description <- `[product_id.supplierinfo_code.code] product_id.supplierinfo_code.name`

The similar module but for sale process in version 11.0 show the same functionality:
 - sale.product_id <- `[product_id.code] product_id.name`
 - sale.description <- `[product_id.supplierinfo_code.code] product_id.supplierinfo_code.name`

And the initial module had this way.
IMHO we should be consistent with the purchase and sale behavior, like the first version of this module in v8.0 and new v11.0, if we like change the sale functionality we should first change the purchase functionality. 

# `product_supplierinfo` functionality 11.0:
 - https://github.com/odoo/odoo/blob/11.0/addons/product/models/product.py
 - ![product supplier info code](https://user-images.githubusercontent.com/6644187/48919287-82deb900-ee57-11e8-8f39-43b26c1017ea.gif)


# `product_supplierinfo_for_customer_sale` functionality 11.0:
 - https://github.com/OCA/sale-workflow/tree/11.0/product_supplierinfo_for_customer_sale
 - ![sale2](https://user-images.githubusercontent.com/6644187/47457200-1e6b0400-d79c-11e8-94fa-0af03370f74d.gif)

**Comment by bunhin** [comment]
Hi, @rafaelbn and @moylop260 ,  i believe the correct behavior should be like v11, for customer code, We search or entry customer code (customer code and name in search windows) because customer will order using their code for example, when the item is selected and saved it should convert to our internal code for product filed, therefore we can understand what internal item code our customer order for.

For supplier code,  we should search by internal code (theoriticaly we know our product name and code better), than when it is selected and saved it should be converted to display the supplier code and name so the supplier can understand better.

So the v10 behavior should be changed to follow like v11

I have One question:
will it possible to import our customer sales order from csv or file excell,  using the customer name and code without internal code?

Thank you

**Comment by rafaelbn** [comment]
Hello @HaraldPanten what do you think?

**Comment by rafaelbn** [comment]
And the migration to v12 is https://github.com/OCA/product-attribute/pull/446
