### ISSUE TITLE
sale_order_price_recalculation do not work with cost when Display margins on quotations and sales orders is enabled

### ISSUE THREAD

**Issue by eversatis** [OCA/sale-workflow#753]
sale_order_price_recalculation do not work with cost when Display margins on quotations and sales orders is enabled. I am using odoo 10.

**Comment by pedrobaeza** [comment]
Can you be more specific? Do you mean that the cost is not updated or what?

**Comment by eversatis** [comment]
Yes, steps to reproduce.
1. Enable 'Display margins on quotations and sales orders' under Sales-Configuration-Settings-Margin.
2. For created quotation, if you click recalculated price, the cost in order lines would be still 0.
3. For new created quotation, if you change pricelist to different currency, the sale price will change but the cost will stay the same and cause the Margin a wrong value.

Thank you!

**Comment by pedrobaeza** [comment]
And that's the expected behavior, as the module only recalculates sales prices. What you ask is a new feature for a new module: `sale_order_margin_recalculation`.

Closing as no issue with current module, but new module to be developed.
