### ISSUE TITLE
[11.0][Bug] Issue on commission analysis: Can not open it

### ISSUE THREAD

**Issue by ghost** [OCA/sale-workflow#769]
Hi guys,

I got this error when trying to open menu Invoicing > Reporting > Management > Commission Analysis.
![screenshot from 2018-12-20 15-13-45](https://user-images.githubusercontent.com/10511982/50272569-cb938d00-046a-11e9-8cb5-563f5396201c.png)

Field `amount` is defined in Abstract model `sale.commission.line.mixin` but it is not re-defined the logic by inherited models `account.invoice.line.agent` and it causes the problem.

**Comment by pedrobaeza** [comment]
Odoo version? Do you have latest code?

**Comment by ghost** [comment]
Version 11.0, I just updated the version to issue's title.I am using the latest source code

**Comment by bodedra** [comment]
@pedrobaeza Seems right place for these issue at https://github.com/OCA/commission module: sale_commission

I can able to reproduce it at runbot.

http://3350927-11-0-9f64c4.runbot1.odoo-community.org/web?debug=1#view_type=list&model=account.invoice&menu_id=136&action=217

**Comment by ghost** [comment]
Ah, My mistake. I already created the new one https://github.com/OCA/commission/issues/194. I will close this one
