### ISSUE TITLE
[10.0][BUG] sale-product-set-layout Error during installation

### ISSUE THREAD

**Issue by labaggio** [OCA/sale-workflow#783]
When I try to install with pip the module sale-product-set-layout following this instructions (https://pypi.org/project/odoo10-addon-sale-product-set-layout/) I get the following error

```
Could not find a version that satisfies the requirement odoo<10.1dev,>=10.0 (from odoo10-addon-sale-product-set-layout) (from versions: )
No matching distribution found for odoo<10.1dev,>=10.0 (from odoo10-addon-sale-product-set-layout)
```

**Comment by pedrobaeza** [comment]
You don't have odoo installed by pip, so that's the problem.

**Comment by labaggio** [comment]
> You don't have odoo installed by pip, so that's the problem.

I'm sorry  '-_-
