### ISSUE TITLE
[11.0] [sale_quotation_number] Sale Order number not genersted if tick Lock Confirmed Orders

### ISSUE THREAD

**Issue by Vassy** [OCA/sale-workflow#791]
If in Sales -> Configurations -> Settings tick Lock Confirmed Orders and untick Use Same Enumeration, Sale order numder not generate. SQ001 - quotation, Confirm Sale - sale order is again SQ001. Espected - SO001.
Tested on Runbot - http://3355835-11-0-056f56.runbot2.odoo-community.org

**Comment by Vassy** [comment]
Any suggestion?

**Comment by ghost** [comment]
Im in the same situation. It is fixed yet?

**Comment by hugho-ad** [comment]
Hello folks!

fixed at https://github.com/OCA/sale-workflow/pull/838, could you test it, please

regards!
