### ISSUE TITLE
[12.0][ADD] Sales Invoice Plan

### ISSUE THREAD

**Issue by kittiu** [OCA/sale-workflow#809]
Hi, we have created and pass all the test for this module - Sales Invoice Plan

By standard feature, user can gradually create partial invoices, one by one. This module add ability to create invoices based on the predefined invoice plan into the future (month/day/year interval or manual), either all at once, or one by one. The plan support both advance invoice and installment invoices.

![00440](https://user-images.githubusercontent.com/1973598/54094599-b7f62380-43d4-11e9-8bc4-12cc6073668f.png)

https://github.com/OCA/sale-workflow/pull/807

**Comment by kittiu** [comment]
Can this be merged? Anything else needed?

**Comment by pedrobaeza** [comment]
Please don't create new issues. You have a PR, so the conversation should be done there.
