### ISSUE TITLE
sale_order_price_recalculation does not log about total price changed

### ISSUE THREAD

**Issue by KaungMAung** [OCA/sale-workflow#848]
module: sale_order_price_recalculation
version: 12.0

**Steps to reproduce**
- ...

**Current behavior**
sale_order_price_recalculation does not log about total price changed
**Expected behavior**
sale_order_price_recalculation  if total price changed, need to log

**Comment by pedrobaeza** [comment]
Try again now

**Comment by EasyPeasyKMA** [comment]
Thanks a lot for fast response. But it is still not logging yet.
![image](https://user-images.githubusercontent.com/15133712/57986590-4b209900-7aa9-11e9-95de-e7fd15382771.png)

**Comment by KaungMAung** [comment]
Dear Pedro,

Thank you so much for super fast response. But Behaviour is still the same. This is what i did:
Odoo 12 EE version:
1. Create Sales order with 4% discount Price List. And save.
2. Edit Sales Order with 20% Pricelist. And Recalculate Price. 
3. Line price and Total price is updated. But It never log into Logging.

![recal](https://user-images.githubusercontent.com/15133712/57986668-82dc1080-7aaa-11e9-9bf6-ff1f970f91b1.jpg)

**Comment by pedrobaeza** [comment]
The module is doing its job, but that side effect is something not covered, so you shouldn't rely on that. I'll add this to the known issues.

**Comment by KaungMAung** [comment]
Dear Pedro,

I fully understand your point. And Thank you so much to you guys for this module. I'm just reporting what we encountered when using this. 

Cheers,
Kaung
