### ISSUE TITLE
We have a module where we calculate the totals by section in the sale order

### ISSUE THREAD

**Issue by agent-z28** [OCA/sale-workflow#869]
You can have a monthly section -> monthly total
and so on! Is there already anything like this?

**Comment by pedrobaeza** [comment]
https://github.com/OCA/sale-reporting/tree/11.0/sale_layout_category_hide_detail includes subtotals in reports as side effect.

**Comment by agent-z28** [comment]
![Bildschirmfoto vom 2019-06-11 13-28-07](https://user-images.githubusercontent.com/7473428/59268340-cb6f8f80-8c4c-11e9-9f91-b9548742e5cd.png)

Thats what we have. 
On Top we can give total discount by category.

**Comment by pedrobaeza** [comment]
Seems interesting, but each feature in one module.
