### ISSUE TITLE
addon not installed in runbot

### ISSUE THREAD

**Issue by jwaes** [OCA/sale-workflow#871]
I wanted to try the add on via the runbot link on this page:
https://github.com/OCA/sale-workflow/tree/12.0/sale_product_set

but the referred add on is not installed in that environment

**Comment by pedrobaeza** [comment]
Why are you opening more issues? This issue tracker is not for helping you in the deployment. For that, use forums or mailing lists.

**Comment by jwaes** [comment]
This is a bug ... this is an error in your documentation. 

So if you don't like it. remove the link on https://github.com/OCA/sale-workflow/blob/12.0/sale_product_set/README.rst

**Comment by pedrobaeza** [comment]
Which error in documentation?

**Comment by jwaes** [comment]
The last icon on the first line of that referenced file has a link to a runbot instance to demo the addon. but the addon is not installed there. if you do not want to maintain the runbot instance, which is an option, then remove the link. But if you keep the link, then make sure that the addon in question is actually available in the runbot instance.

**Comment by pedrobaeza** [comment]
The module is there, so no error:

![Peek 11-06-2019 16-50](https://user-images.githubusercontent.com/7165771/59282382-1f886d00-8c69-11e9-9bca-f890bbeffaca.gif)

**Comment by jwaes** [comment]
Ok my mistake, i thought it was an app, while it is a module
