### ISSUE TITLE
duplicate key value violates unique constraint ir_model_data_pkey

### ISSUE THREAD

**Issue by tahitahi** [OCA/sale-workflow#898]
Hello,

I get the following error message when install :

odoo duplicate key value violates unique constraint ir_model_data_pkey DETAIL: Key (id)=(11063) already exists.

Thank you for helping and kind regards

**Comment by pedrobaeza** [comment]
You have messed up somehow your DB sequence for that model (ir_model_data), putting a nextval for `id` that is already present on your table.

This has nothing to do with any module (whatever it is, as you don't even include the name).

Closing as no issue with the module.
