### ISSUE TITLE
[11.0][sale_order_line_date] Question about usage

### ISSUE THREAD

**Issue by rgl1234** [OCA/sale-workflow#914]
Hello
I have a question related to sale_order_line_date module.

I understand how to add specific dates on every SO-line. Then when I validate the SO, the nearest date is set as sceduled-date on the "stock.picking". The dates of the SO-line are available on the "stock.move".

My problem now is, that on the picking it is not obvious, that not all products should be shipped at the same time, because there is only visible the sceduled-date of the picking and no information about the specific dates on the stock.move.

Then when someone validates the picking because it is ready, all stock-moves are validated even if they should not be shipped yet....

So what I would expext here is, that on validating an SO with different dates on SO-lines, several individual stock-pickings are created for that particular SO. But this does not happen.....

So how do you handel this situation?

Thans
René

**Comment by LoisRForgeFlow** [comment]
You would need this module in v11: https://github.com/OCA/sale-workflow/pull/668

**Comment by rgl1234** [comment]
> You would need this module in v11: #668

@lreficent 
Thanks for this information. It seems that this would solve my problem. But do you now why this functionality is not already by default implemented in sale_order_line_date ? I cannot find an answer why it helps to have different dates on every SO-line when then I cannot ship it at the requested date.
Am I maybe missing something here? What is the sence to have seperate dates on every SO-line and do not split the pickings?

**Comment by nithwith** [comment]
Same needs, thanks for the module @LoisRForgeFlow
