### ISSUE TITLE
[12.0] Element '<xpath expr="//input[@type='text'][hasclass('quantity')]">' cannot be located in parent view

### ISSUE THREAD

**Issue by patel1008b** [OCA/sale-workflow#921]
**Getting this Error while installation sale_automatic_workflow module.**

Element "<xpath expr="//input[@type='text'][hasclass('quantity')]">" cannot be located in parent view

Error context:
View `Shopping Cart Lines`
[view_id: 1297, xml_id: n/a, model: n/a, parent_id: 945]
None" while parsing None:10, near

**Comment by pedrobaeza** [comment]
You have modified your Odoo so that the module fails to install. Try on a fresh database or fix your current DB.

**Comment by patel1008b** [comment]
@pedrobaeza Yes, tried new fresh DB, it's only working if you have installed sale_stock module without mention this module in addons path then mention this in addons path and install it.

But if simply make a new fresh DB, the first module install to be install **sale_automatic_workflow**
it breaks again.

**Comment by pedrobaeza** [comment]
`sale_stock` module is put as dependency in the module:

https://github.com/OCA/sale-workflow/blob/659837a97a6abe9c34c6c56954753054c5660606/sale_automatic_workflow/__manifest__.py#L17

so that can't be the reason.
