### ISSUE TITLE
[11.0][12.0][13.0] Show untaxed amount in all the sale.order views (quotation and sale orders)

### ISSUE THREAD

**Issue by rafaelbn** [OCA/sale-workflow#928]
Hi all @OCA/crm-sales-marketing-maintainers ,

Odoo is used mainly by Companies who care the amount untaxed of the sale and not Total (including taxes). As Taxes are... taxes.

So it would be very nice to have untaxed amount

![untaxed](https://user-images.githubusercontent.com/8736623/64164268-2e835380-ce43-11e9-831e-6def0c8e30d6.png)

Please @fgi-odoo take care on this in v13! I have check it and it also not selectable!!! :pray: 

![untaxed amount missing](https://user-images.githubusercontent.com/8736623/64164385-730eef00-ce43-11e9-9c6a-4569f9a8ae8e.png)

**Comment by yajo** [comment]
Fix for v13: https://github.com/odoo/odoo/pull/36366

**Comment by rafaelbn** [comment]
Closing as fixed in Odoo master :tada:
