### ISSUE TITLE
[RFC] Sale General Terms

### ISSUE THREAD

**Issue by dreispt** [OCA/sale-workflow#938]
### Specification

This Module should allow to create sales terms ("General Selling Consitions") for different countries and languages.

- It should allow to work on drafts version of the existing terms.
- Suggest matching sales terms based on Customer's country and language
- The matching sales terms should be selected and shown as the last page(s) of the Quotation and Sale Order.

**Comment by pedrobaeza** [comment]
Isn't this what `agreement_sale` does? cc @max3903

**Comment by dreispt** [comment]
Thank for commenting Pedro.
AFAICS Agreements are contract specific conditions, thus tied o a particular customer.
My requirement is for general sale conditions texts, per country/region and language.

**Comment by pedrobaeza** [comment]
Maybe expanding `agreement` for being tied to country, region or global through fields in that agreements?

**Comment by dreispt** [comment]
I can surely consider that option.

Do you think it conceptually fits in the "Agreement" concept? I'm concerned this might be a long stretch and can confuse users.

Do you see clear benefits in tying together both features? From an implementation PoV I have the feeling that it would complicate both.

**Comment by pedrobaeza** [comment]
I can't say as I haven't dug too much in that modules, but only being early reminder in case of starting divergence approaches. That's why I have pong @max3903 for having his opinion.

**Comment by dreispt** [comment]
I've learned more about Agreements now.
This is about the generic contract "small letters" you copy at the end of every SO, not specific sale/contract conditions. 
So I believe that it is a distinct feature.

**Comment by pedrobaeza** [comment]
Ok, great
