### ISSUE TITLE
[11.0][sale_blanket_order] supplier_taxes_id

### ISSUE THREAD

**Issue by gbaumgartner-callino** [OCA/sale-workflow#960]
Hello,
I was just trying out sale_blanket_order and I don't quite understand why sale.blanket.order.line would use supplier_taxes_id instead of taxes_id.

It creates sale.order.line records which use taxes_id after all.

Can someone explain the reasoning behind this, or is this a legit oversight?

Thanks!

**Comment by francesco-ooops** [comment]
This issue is also present on 12.0, tested on runbot

When a new blanket order line is added > purchase tax is used

![image](https://user-images.githubusercontent.com/55489873/109485146-9b4fcc00-7a81-11eb-90b2-f23738e44860.png)
