### ISSUE TITLE
[RFC] New repository: sale_discount

### ISSUE THREAD

**Issue by rousseldenis** [OCA/sale-workflow#985]
As mentionned by @lmignon in #729, and in order to decrease sale-workflow repository module numbers, we should try to identify some groups of modules that cover the same functional area.

For a start, why not creating a repository 'sale_discount' ?

@rafaelbn @pedrobaeza @lmignon @Cedric-Pigeon @OCA/crm-sales-marketing-maintainers

**Comment by pedrobaeza** [comment]
Which are the candidates for this repo?

**Comment by rousseldenis** [comment]
All sale_promotion_rule* (see v10), sale_discount_display_amount, sale_fixed_discount, ... and other I haven't found yet

**Comment by pedrobaeza** [comment]
Then I would call it `sale-price` or similar.

**Comment by rousseldenis** [comment]
Yes, that could be

**Comment by rousseldenis** [comment]
You want me to call for that new repo on contributors mailing list ?

**Comment by rousseldenis** [comment]
After discussion with colleagues, it was more oriented 'promotion', to restrict the scope. So sale-promotion is better

**Comment by lmignon** [comment]
I'm in favor of `sale-promotion`

**Comment by pedrobaeza** [comment]
OK about the name. You have to write to contribute at odoo-community dot org for asking for the repository.

**Comment by pedrobaeza** [comment]
@rousseldenis have you written to `contributors` instead of `contribute`?

**Comment by rousseldenis** [comment]
> @rousseldenis have you written to `contributors` instead of `contribute`?

Yes, but never heard for contribute...

https://odoo-community.org/groups

**Comment by pedrobaeza** [comment]
That's not a mailing list, but the alias of a project in OCA instance for creating the task for doing it, and it's the place to do the request (but not sure where is that documented inside OCA website).

**Comment by rousseldenis** [comment]
> (but not sure where is that documented inside OCA website).

:smile: Ok, that's two different things. Will do it
