### ISSUE TITLE
Question - Can't enable sale_merge_draft_invoice

### ISSUE THREAD

**Issue by 3DOeste** [OCA/sale-workflow#989]
Hi, I can't enable the merge invoice function after installing the module, the checkbox is greyout. Do I need something else?

Odoo 12, Ubuntu 18.04.

**Comment by bodedra** [comment]
I hope, you have activated `Merge new invoices with existing draft ones` from `Sales > Configuration > Settings` after install module.

**Comment by 3DOeste** [comment]
Hi, I tried but the setting is grey out and can’t be enabled. Does it need another configuration?

**Comment by bodedra** [comment]
@3DOeste : I have fixed issue at #991 so you can test it here for now http://3395659-991-105138.runbot1-2.odoo-community.org/web?#id=&action=420&model=res.config.settings&view_type=form&menu_id=253

once it approve, you can take a pull of sale_merge_draft_invoice module and try it on your database.

**Comment by 3DOeste** [comment]
Thanks, I modified the files as the PR and it’s working now!

**Comment by bodedra** [comment]
@3DOeste That's great. You can approve that PR, it will help to merge fast.

**Comment by pedrobaeza** [comment]
Fixed in #991
