### ISSUE TITLE
[RFC] sale_product_returnable

### ISSUE THREAD

**Issue by max3903** [OCA/sale-workflow#993]
Depends on sale_stock

This module allows you to set some product as returnable and create a reception when the sales order is confirmed.

An example is for beverage distributors where their customer order beverage in bottles and the empty bottle should be returned.

# Configuration

* Go to Inventory > Master Data > Products
* Create or select a product (like Bottle of Water)
* Go to the Inventory tab
* Edit the product to check the box "Can be returned?"
* Select the product to be returned (Empty Bottle)

# Usage

* Go to Sales
* Select or create a quotation
* Add the product (Bottle of Water) to the lines 
* Confirm the quotation
* Go to Inventory
* Check the Receipts to make sure you have a receipt for the returned product (Empty Bottle). By default, the expected quantity is set to the same as the one delivered.

# Technical Specifications

## product.template

- [x] Add a boolean field "Can be returned?" (returnable)
- [x] Add a many2one field "Returned Product" (return_product_id) to product.template
- [x] Show the "Returned Product" field if "Can be returned?" is True. Make it required.

## sale.order

- [x] When the sale order is confirmed, if the sale order lines contain a returnable product, create a picking using:
* the return operation of the original operation
* the same customer
* the same date
* the returned product
* the same quantity

**Comment by rousseldenis** [comment]
>  When the sale order is confirmed, if the sale order lines contain a returnable product, create a picking using:

@max3903 Does that flow could lead to many pending pickings and have some of them unused if customer never comes back.

Wouldn't it be better to create picking from sale on the flight at the returning moment ?

**Comment by max3903** [comment]
@rousseldenis We are implementing Odoo for a water distributor. Their rule is to deliver the same quantity of full bottles than the quantity of empty ones the customer return. The return and delivery happens at the same time and will both be available to the driver on the field service order.

So to answer yours questions, there would not be unused pickings and there is no reason to create the return on the fly. I am not sure, but the return like the delivery order may need to be printed the day before.

**Comment by rousseldenis** [comment]
Ok, IMHO that should be an option to check. To allow both behaviours. In most of retails I know, you buy bottles and then you bring them back or not to the same supplier. That was I had in mind when I write my remark.

**Comment by rousseldenis** [comment]
That introduces also the 'consignee' (for bottles, ...) management concept. But maybe this is out of scope of this.
